-- ============================================================
-- Content quality fix: body/read_more continuity
-- 21 entries rewritten so read_more continues body's thought
-- instead of rewinding or restating.
-- Run this in the Supabase SQL editor.
-- ============================================================

UPDATE entries SET
  body = 'The pre-Julian Roman calendar was a political instrument deliberately manipulated by officials to extend their terms or disadvantage opponents — so chaotic that by 46 BCE the calendar was 80 days out of sync with the solar year.',
  read_more = 'Caesar''s solution required first correcting the accumulated drift: 46 BCE was decreed a "year of confusion" of 445 days — the longest year in Roman history — to realign the calendar with the seasons. He then consulted the Alexandrian astronomer Sosigenes and introduced a 365.25-day solar year, adding a leap day every four years. The Julian calendar was used throughout Europe for 1,600 years. Its only flaw was slight over-correction: the true solar year is 11 minutes shorter than 365.25 days, which accumulated to a 10-day discrepancy by the 16th century. Pope Gregory XIII commissioned the Gregorian reform in 1582 — dropping 10 days and adjusting the leap year rule — and the new calendar was adopted at different times across Europe, with Russia not switching until 1918.'
WHERE id = '33333333-0003-0016-0003-000000000003';

UPDATE entries SET
  body = 'Free throw accuracy in NBA games is approximately 75% — surprisingly low for an uncontested, standardized shot from a fixed spot. NBA players typically shoot 85–90% in practice, meaning the 10–15 percentage point drop in games is not explained by physical difficulty alone.',
  read_more = 'The explanation is explicit monitoring theory: the conscious attention triggered by high stakes disrupts the automated motor program that normally runs the shot. Pre-shot routines — the bouncing, spinning, and deep breathing that look like superstition — are cognitively functional: they give the conscious mind something to do so it stops interfering with the motor sequence. Players with more consistent routines show smaller accuracy drops under late-game pressure. The strategic consequence has been significant: the "hack-a-Shaq" foul-on-purpose tactic (targeting poor free throw shooters like Shaquille O''Neal, who shot 52% from the line) transformed NBA late-game strategy around a single psychological vulnerability, forcing rule changes to limit its use.'
WHERE id = '44444444-0004-0017-0004-000000000004';

UPDATE entries SET
  body = 'Insurance is one of humanity''s oldest financial innovations — the Code of Hammurabi (1754 BCE) included provisions for marine loans that were forgiven if cargo was lost at sea, a primitive form of risk pooling. The first true insurance contracts appeared in 14th-century Genoa and Venice: merchants pooled risk against ship losses for a fee, separating the transfer of risk from the underlying loan.',
  read_more = 'From this Mediterranean foundation the industry grew outward. Lloyd''s of London began as a coffee house in 1688 where merchants and ship captains gathered to share risk on individual voyages — each underwriter signing for a share rather than the whole. The Great Fire of London in 1666, which destroyed roughly 13,000 homes, created the political will for fire insurance infrastructure and organized fire brigades. Life insurance developed through the 18th century as actuarial mathematics advanced — Edmond Halley (of comet fame) produced the first mortality tables in 1693. The modern insurance industry works because risk is predictable at scale even when individual outcomes are not: you cannot know if your house will burn, but an actuary can estimate the fraction of 100,000 houses that will burn within a year, allowing premiums to be priced with precision.'
WHERE id = '55555555-0005-0014-0005-000000000005';

UPDATE entries SET
  body = 'Homeostasis is the body''s tendency to maintain stable internal conditions — temperature, blood sugar, pH, oxygen levels — despite external changes. It is the defining property of living systems and operates through feedback loops.',
  read_more = 'Negative feedback is the core mechanism: a sensor detects deviation from a set point, and effectors act to correct it. Body temperature illustrates this precisely — when core temperature rises, sweat glands activate and surface blood vessels dilate to dissipate heat; when it falls, shivering generates heat and vasoconstriction preserves it. Blood glucose is regulated by opposing hormones: insulin (secreted by the pancreas when glucose is high) drives glucose into cells; glucagon (secreted when glucose is low) triggers glycogen breakdown in the liver. Type 1 diabetes is a failure of insulin production; Type 2 is a failure of insulin response — both expose how dependent survival is on this one feedback loop. The concept has been extended beyond physiology: allostasis describes set points that shift based on anticipated demands rather than simply correcting deviations after the fact.'
WHERE id = '66666666-0006-0012-0006-000000000006';

UPDATE entries SET
  body = 'The word "bug" for an engineering defect predates computers — Thomas Edison used it in 1878 and it appears throughout 19th-century mechanical engineering. But the term got its most memorable computer-specific illustration on September 9, 1947, when Grace Hopper''s team at Harvard found a moth trapped in a relay of the Mark II computer, and taped it into the logbook with the note "First actual case of bug being found."',
  read_more = 'The logbook, now preserved at the Smithsonian Institution''s National Museum of American History, is the most famous artifact in computing history. Hopper herself went far beyond it: she developed the first compiler (A-0 system, 1952), which translated human-readable code into machine instructions — a conceptual leap that transformed programming from machine-specific to language-agnostic work. She later led the design of COBOL, the business programming language that still runs significant portions of banking and government infrastructure today. She championed the idea that programming should be accessible without deep hardware knowledge — a philosophy that shaped every high-level language that followed. Hopper was awarded the National Medal of Technology in 1991 and the Presidential Medal of Freedom posthumously in 2016.'
WHERE id = '77777777-0007-0010-0007-000000000007';

UPDATE entries SET
  body = 'The invention of photography (1839) threatened to make realistic painting obsolete — and instead liberated painting from its documentary function, directly enabling Impressionism, Post-Impressionism, and the entire trajectory of modern art.',
  read_more = 'Freed from documentation, painters began pursuing what the camera could not capture: movement, subjective light, emotion, and the painter''s own perceptual act. Monet''s serial paintings of haystacks and Rouen Cathedral at different times of day were explicitly exploring the camera''s blind spot — treating the same scene at dawn and dusk as different subjects. Cézanne abandoned the single fixed viewpoint entirely, painting multiple simultaneous perspectives into one canvas. Muybridge''s motion photography (1878) had an ironic corrective effect: it revealed that painters had been depicting galloping horses incorrectly for centuries, and painters quickly adopted accurate motion. Photography also changed the painter''s relationship to source material — working from photographs became possible, enabling Degas''s intimate, seemingly candid compositions that would have been impossible to hold as live poses. The camera did not kill painting; it changed its job description.'
WHERE id = '88888888-0008-0013-0008-000000000008';

UPDATE entries SET
  body = 'The Medici banking dynasty''s investment in Renaissance art was not purely aesthetic — it was strategic, converting financial wealth (socially suspect under Church usury prohibitions) into cultural capital and political legitimacy through visible patronage of churches and public works.',
  read_more = 'The Church condemned usury (charging interest), which created a specific problem for bankers: great wealth and social stigma simultaneously. Cosimo de'' Medici''s solution was systematic: fund the dome of Florence''s Cathedral, commission Ghiberti''s Baptistery doors, support Donatello — embedding Medici imagery in civic religion and buying theological legitimacy through visible piety. Lorenzo de'' Medici extended this to Botticelli, Leonardo, and the teenage Michelangelo, transforming Florence into Europe''s cultural capital and the Medici name into a byword for civilization rather than lending. Richard Goldthwaite''s economic history of Renaissance patronage shows the art market was a sophisticated system of competitive contracts and reputation management, not spontaneous cultural flowering. The model is recognizable today: tech billionaire philanthropy follows the same logic of converting financial capital into cultural and civic legitimacy.'
WHERE id = '88888888-0008-0014-0008-000000000008';

UPDATE entries SET
  body = 'Social proof is the tendency to use others'' choices as information about the correct behavior in ambiguous situations. It explains why restaurants post "most popular" items, why Amazon displays review counts, and why laugh tracks work.',
  read_more = 'The evolutionary logic is simple: in a world where gathering information is costly, others'' behavior provides free signals about what is safe, desirable, or correct. The effect scales with similarity — we weight behavior from people like us most heavily, which is why "most popular among people in your city" outperforms generic popularity counts. Asch''s conformity experiments (1951) showed participants giving obviously wrong answers to simple perceptual questions when surrounded by confederates giving the same wrong answers — not from stupidity but from treating social consensus as evidence. Cialdini''s field research showed that hotel towel reuse increased when signs said "most guests in this room reuse their towels" versus generic environmental appeals. Critically, negative social proof backfires: framing a problem as widespread (most people don''t comply) increases non-compliance. The correct design always shows the majority doing the right thing, never the majority doing the wrong one.'
WHERE id = '99999999-0009-0013-0009-000000000009';

UPDATE entries SET
  body = 'Noam Chomsky proposed that all humans share an innate "universal grammar" — a biological faculty with core structural properties common to all languages. The theory has been enormously influential and enormously contested.',
  read_more = 'The poverty of the stimulus argument is Chomsky''s core claim: children acquire complex grammatical structures faster and more uniformly than the impoverished, error-filled input they receive could explain — suggesting that much of the structure is built in. Specific cross-linguistic patterns seemed to confirm this: all languages have nouns and verbs; all appeared to have recursion. The challenges, however, are substantial. Daniel Everett''s analysis of Pirahã (an Amazonian language) claims it lacks recursion entirely — fiercely disputed but unresolved. The World Atlas of Language Structures documents enormous structural variation that any proposed universal must explain away. More fundamentally, usage-based theories (Tomasello, Goldberg) argue that grammar emerges from statistical learning of patterns in language input rather than innate structure — and neural network models that learn grammar from input alone have complicated the poverty-of-stimulus argument empirically.'
WHERE id = 'bbbbbbbb-000b-0007-000b-00000000000b';

UPDATE entries SET
  body = 'Children acquire language virtually effortlessly in early childhood; adults learning a second language rarely achieve native-like proficiency. Eric Lenneberg proposed the critical period hypothesis in 1967: between ages 2 and puberty, the brain''s plasticity is optimal for language acquisition, and after puberty, native-level proficiency becomes essentially unattainable regardless of effort.',
  read_more = 'The evidence converges from multiple directions. Children of immigrants achieve native-like accents in the new country regardless of how long they have been exposed; their parents, arriving as adults, typically retain foreign accents after decades of immersion — the critical asymmetry Lenneberg predicted. Brain damage to language areas in children is recovered from far more completely than equivalent adult damage, reflecting preserved plasticity. The case of Genie — a girl discovered at age 13 having been completely isolated with no language exposure — confirmed the hypothesis tragically: despite years of intensive therapy, she never acquired normal grammar, though vocabulary and pragmatic competence developed. Neuroimaging shows that late language learners process their second language in partly different brain regions from native speakers. The cutoff is not sharp: outcomes are best for learners who begin before age 8, good for beginners before puberty, and diminish progressively after that.'
WHERE id = 'bbbbbbbb-000b-0016-000b-00000000000b';

UPDATE entries SET
  body = 'Many forest ecosystems evolved with regular fire and depend on it for ecological health. Fire clears accumulated deadwood, releases locked-up nutrients, and creates the open conditions some species require for germination and habitat — making periodic burning a feature of these ecosystems, not a threat.',
  read_more = 'Lodgepole pine and giant sequoia have serotinous cones: sealed with resin, they only open to release seeds when heated by fire, ensuring regeneration immediately after a burn when competing vegetation has been cleared and nutrients released. Without fire, organic matter accumulates into fuel loads that transform manageable surface fires into catastrophic crown fires that burn hot enough to sterilize soil and kill even the seeds adapted to survive. A century of aggressive suppression created exactly this backlog across the American West. Indigenous communities in Australia had used cultural burning for 50,000+ years to maintain productive, fire-resilient landscapes — a practice now being integrated into formal fire management alongside prescribed burns. The challenge is not whether to burn but how to work through decades of accumulated fuel safely.'
WHERE id = 'cccccccc-000c-0005-000c-00000000000c';

UPDATE entries SET
  body = 'Mangrove forests — coastal trees adapted to saltwater — store carbon in their soils up to 10 times faster per hectare than tropical rainforests, making them among the most carbon-dense ecosystems on Earth. They also protect coastlines from storm surge, filter water, and provide nursery habitat for fish.',
  read_more = 'The exceptional carbon storage comes from the mechanism: mangroves sequester carbon primarily in anaerobic, waterlogged soils where decomposition is extremely slow, building deep organic layers over centuries that persist long after individual trees die. Unlike above-ground forest carbon, which is released rapidly when trees burn, mangrove soil carbon can remain locked away for millennia. Global mangrove cover has declined roughly 35–50% since the 1980s — driven by shrimp aquaculture, coastal development, and logging — releasing this ancient stored carbon back into the atmosphere. Indonesia, which holds the world''s largest mangrove area, now includes mangrove protection in its national climate commitments. Restoration efforts have shown mixed results at scale, largely because of poor site selection and species matching rather than any fundamental biological barrier.'
WHERE id = 'cccccccc-000c-0014-000c-00000000000c';

UPDATE entries SET
  body = 'For most of human history, sugar was an expensive luxury. In medieval Europe it was sold by the gram at apothecaries as a medicine or spice. The industrialization of sugar production in the 18th–19th centuries collapsed its price and transformed the global diet.',
  read_more = 'The price collapse came in two phases. First, Caribbean plantation agriculture — powered by enslaved labor — massively expanded cane sugar supply in the 17th and 18th centuries, dropping prices enough for European middle-class use. Second, Napoleon''s promotion of beet sugar (to break the British naval blockade on cane imports) and subsequent mechanization extended sugar access to the poor. By 1900 sugar was a pantry staple; by 1950 the processed food industry was engineering product palatability around it. Global per-capita sugar consumption rose from roughly 2 kg per year in 1800 to over 20 kg today. The obesity and metabolic disease epidemics of the late 20th century are inseparable from this transformation — a 200-year economic shift that changed what humans eat more profoundly than any culinary trend.'
WHERE id = 'dddddddd-000d-0007-000d-00000000000d';

UPDATE entries SET
  body = 'Coffee is one of the world''s most valuable traded commodities — behind only crude oil. Over 2.25 billion cups are consumed daily worldwide. The global supply chain spans more than 50 producing countries and supports the livelihoods of approximately 125 million people.',
  read_more = 'The journey from Ethiopian highlands to global commodity happened in distinct steps. Coffee spread from Ethiopia to Yemen, where Sufi monks used it to sustain nighttime prayers; Ottoman coffeehouses became centers of intellectual and political life by the 16th century. European coffeehouses — nicknamed "penny universities" because anyone could enter for the price of a cup — incubated major institutions: Lloyd''s of London started in a coffeehouse; the London Stock Exchange emerged from Jonathan''s Coffee House. Today two species dominate: Arabica (Coffea arabica) commands the specialty market for its complex flavor, while Robusta (C. canephora) is cheaper, higher in caffeine, and used in espresso blends and instant coffee. Despite the industry''s scale, commodity prices on the ICE exchange are notoriously volatile — smallholder farmers, who grow roughly 70% of the world''s coffee, frequently receive a fraction of the retail price regardless of which country they''re in.'
WHERE id = 'dddddddd-000d-0010-000d-00000000000d';

UPDATE entries SET
  body = 'The word "salary" derives from the Latin salarium, believed to reference salt payments given to Roman soldiers. Salt was one of the first traded commodities in human history — scarce, essential for food preservation, and valuable enough to anchor trade routes, tax systems, and empires.',
  read_more = 'Because salt was the primary means of food preservation before refrigeration, cities and trade routes were established near salt sources or coastlines. The Saharan salt trade saw slabs of rock salt exchanged weight-for-weight with gold across sub-Saharan Africa — one of medieval Africa''s most important commercial networks. Salt taxes have triggered major historical confrontations: the French gabelle was one of the most despised elements of the ancien régime, fueling revolutionary grievances; Gandhi''s Salt March in 1930 was a deliberately chosen symbolic assault on the British colonial salt monopoly — a tax that hit the poor hardest. The industrial era made salt so cheap that its monetary significance vanished entirely; it is now one of the least expensive food commodities by weight, a complete reversal of its historical status.'
WHERE id = 'dddddddd-000d-0013-000d-00000000000d';

UPDATE entries SET
  body = 'Chocolate was consumed for approximately 3,000 years before Europeans added sugar to it. The Olmec, Maya, and Aztec drank cacao as a bitter, often spiced beverage used in ritual, medicine, and elite consumption — the sweet solid bar was an industrial invention that came nearly 3,500 years later.',
  read_more = 'The Spanish brought cacao to Europe in the 16th century, initially as a medicine; sugar was gradually added to make it palatable, and chocolate houses became fashionable in 17th-century England. The transformation into modern chocolate required two industrial breakthroughs in close succession: Coenraad van Houten''s 1828 hydraulic press separated cocoa butter from cocoa solids, creating both Dutch-process cocoa powder and the precondition for solid chocolate; J.S. Fry & Sons created the first moldable chocolate bar in 1847 by recombining the press''s outputs with sugar. Henri Nestlé and Daniel Peter added condensed milk in 1875, creating milk chocolate and establishing the flavor profile that dominates the market today. The modern industry depends heavily on West African cacao — roughly 70% of world supply comes from Côte d''Ivoire and Ghana — with persistent documentation of child labor and deforestation in those supply chains.'
WHERE id = 'dddddddd-000d-0019-000d-00000000000d';

UPDATE entries SET
  body = 'David Hume demonstrated in the 1730s that inductive reasoning — inferring general principles from observed cases — cannot be rationally justified. The sun has risen every day in recorded history, but this gives us no logical guarantee it will rise tomorrow.',
  read_more = 'The problem exposes a circularity at the heart of empirical knowledge. Justifying induction requires the "uniformity of nature" assumption — that the future will resemble the past. But the only evidence for that assumption is itself inductive (the future has resembled the past so far). Every attempt to justify induction non-circularly runs into this wall. Kant found the threat serious enough to restructure his entire epistemology around it, arguing that the mind imposes causal structure on experience rather than deriving it inductively. Karl Popper''s response was to abandon induction altogether: science does not confirm theories, it attempts to falsify them — a deductive rather than inductive process. But Popper''s falsificationism faces the Duhem-Quine problem: no experiment targets a single hypothesis in isolation; auxiliary assumptions are always involved, making clean falsification impossible. The problem remains genuinely unsolved, which is philosophically significant because the entire edifice of empirical science rests on inferential moves that cannot be formally justified.'
WHERE id = 'eeeeeeee-000e-0007-000e-00000000000e';

UPDATE entries SET
  body = 'Compatibilism is the position that free will and determinism are not contradictory. Most contemporary philosophers are compatibilists: what matters for free will is not whether our actions are causally determined, but whether they flow from the right kind of internal process.',
  read_more = 'The compatibilist move is to redefine what "free" means in a way that survives causal determination. Acting freely, on this view, means acting without coercion, acting from one''s own desires and considered reasons, and being responsive to evidence and argument — not acting from causes that originate entirely outside yourself (compulsion, manipulation, addiction). Harry Frankfurt refined this with his account of second-order desires: we are free when our second-order desire (what we want to want) aligns with our first-order motivation. P.F. Strawson argued from a different angle: concepts like praise, blame, and moral responsibility are grounded in our reactive attitudes toward each other, and these practices are not undermined by determinism — they operate in a different register from causal explanation. Incompatibilists counter that compatibilism simply redefines "freedom" without addressing whether anyone could ever have done otherwise, which is the question that matters for genuine moral responsibility.'
WHERE id = 'eeeeeeee-000e-0013-000e-00000000000e';

UPDATE entries SET
  body = 'Fashion trends historically moved in a "trickle-down" pattern — from elite designers to mass market. Today, street fashion, youth subcultures, and social media have largely inverted this: trends increasingly "trickle up" from the street to the runway, and cycle far faster than they used to.',
  read_more = 'Georg Simmel described the trickle-down mechanism in 1904: elites adopt a fashion to distinguish themselves; lower classes imitate it; elites abandon it for new distinctions — an endless status arms race. The inversion began with 1960s youth culture (jeans, sneakers, band t-shirts) influencing high fashion and intensified as streetwear — rooted in skateboarding, hip-hop, and athletics — became dominant in luxury markets. Supreme''s collaboration with Louis Vuitton and Nike''s designer partnerships brought street aesthetics into the highest price tiers. Social media has compressed cycle times further: a trend that once took years to travel from underground to mainstream now takes months, sometimes weeks. The result is what critics call "fashion at the speed of culture" — and a growing sustainability crisis, with fast fashion companies producing dozens of micro-collections per year and the industry responsible for roughly 10% of global carbon emissions.'
WHERE id = 'ffffffff-000f-0008-000f-00000000000f';

UPDATE entries SET
  body = 'The handshake is often said to date to ancient times as a gesture of peace — showing the right hand empty, demonstrating no weapon. Its exact origin is uncertain, but it appears in ancient Greek and Roman art in contexts of treaty-making and oath-giving, and its modern equalizing form was spread by Quakers in the 17th century.',
  read_more = 'The Quakers (Society of Friends) were particularly significant in popularizing the handshake as a consciously egalitarian greeting: unlike bowing, which encodes social rank, a handshake signals that two people stand as equals — a radical idea in early modern class-stratified Europe. This made it a natural fit for the democratic and commercial cultures of the 18th and 19th centuries, where it became the standard greeting in business and civic life. The gesture varies considerably across cultures today: in many East Asian and South Asian contexts, bowing or pressing hands together serves the same function; in some Middle Eastern cultures, same-gender handshakes are warm and extended while opposite-gender contact between non-intimates is avoided. COVID-19 prompted serious discussion of alternatives, but the handshake appears to be recovering its position as the default professional greeting in most Western contexts.'
WHERE id = 'ffffffff-000f-0013-000f-00000000000f';

UPDATE entries SET
  body = 'Carnival, Mardi Gras, Holi, and similar festivals temporarily invert or suspend normal social hierarchies, rules, and identities. Anthropologists call this state "liminality" — a threshold condition where ordinary structure is dissolved, identities are unstable, and community bonds are renewed through shared transgression.',
  read_more = 'Victor Turner, extending Arnold van Gennep''s three-phase model of rites of passage (separation → liminality → reincorporation), showed that liminal states produce "communitas" — a spontaneous, non-hierarchical solidarity that cannot exist within everyday structured social life. In carnival traditions, the specific mechanisms of inversion are consistent across cultures: masks dissolve identity and status; class hierarchies are satirized; normally forbidden behaviors are temporarily licensed. Turner''s insight was that this inversion is structurally necessary — the experience of communitas, however brief, reminds participants that the hierarchies they live within are social constructions, not natural facts. The "safety valve" theory argues this is exactly why ruling classes historically tolerated carnival: by releasing social tension periodically, it made the return to hierarchy more tolerable. Critics (Stallybrass and White) counter that carnival spaces also generate genuine resistance and social critique that outlasts the festival — the permitted transgression creating a template for the impermissible one.'
WHERE id = 'ffffffff-000f-0014-000f-00000000000f';
