-- ============================================================
-- Trivia Seed: 240 questions (15 per category × 16 categories)
-- ============================================================

-- ---- MUSIC (a1111111) ----
INSERT INTO trivia_questions (id, category_id, question, choices, correct_index, explanation, difficulty) VALUES
('a1111111-0000-0000-0000-000000000001','music','Which composer wrote "The Four Seasons"?','["Antonio Vivaldi","Johann Sebastian Bach","Wolfgang Amadeus Mozart","George Frideric Handel"]',0,'Vivaldi composed "The Four Seasons" (Le quattro stagioni) around 1720 as a set of four violin concertos.','easy'),
('a1111111-0000-0000-0000-000000000002','music','What is the standard concert pitch frequency for the note A4?','["432 Hz","440 Hz","438 Hz","442 Hz"]',1,'A4 = 440 Hz was adopted as the international standard by the ISO in 1955.','easy'),
('a1111111-0000-0000-0000-000000000003','music','How many strings does a standard violin have?','["4","5","6","3"]',0,'A standard violin has four strings tuned G, D, A, and E.','easy'),
('a1111111-0000-0000-0000-000000000004','music','What term describes two or more conflicting rhythms played simultaneously?','["Polyrhythm","Syncopation","Ostinato","Rubato"]',0,'Polyrhythm involves layering two or more distinct rhythms at the same time, common in West African music and jazz.','medium'),
('a1111111-0000-0000-0000-000000000005','music','Which time signature is known as "common time"?','["3/4","6/8","4/4","2/2"]',2,'4/4 is called common time because it is the most frequently used time signature in Western music.','easy'),
('a1111111-0000-0000-0000-000000000006','music','What is an "earworm" in music psychology?','["A microphone defect","Involuntary musical imagery stuck in the mind","A technique for memorising scales","A type of bass frequency"]',1,'Earworms (involuntary musical imagery) affect about 98% of people; repetitive, simple melodies are most prone to becoming earworms.','medium'),
('a1111111-0000-0000-0000-000000000007','music','Which interval ratio defines an octave?','["2:1","3:2","4:3","5:4"]',0,'An octave represents a 2:1 frequency ratio — the higher note vibrates exactly twice as fast as the lower.','medium'),
('a1111111-0000-0000-0000-000000000008','music','What is the name of the Beethoven symphony that features "Ode to Joy"?','["Fifth Symphony","Seventh Symphony","Ninth Symphony","Sixth Symphony"]',2,'Beethoven''s Ninth Symphony (1824) contains the famous choral finale based on Schiller''s "Ode to Joy."','easy'),
('a1111111-0000-0000-0000-000000000009','music','Which West African instrument is considered a direct ancestor of the banjo?','["Kora","Akonting","Balafon","Djembe"]',1,'The akonting, a folk lute of the Jola people of Senegambia, shares key structural and playing features with the early banjo.','hard'),
('a1111111-0000-0000-0000-000000000010','music','What does "fortissimo" mean in musical notation?','["Very soft","Moderately loud","Very loud","At a moderate pace"]',2,'Fortissimo (ff) means "very loud" in dynamic markings; it is louder than forte (f).','easy'),
('a1111111-0000-0000-0000-000000000011','music','The 12-bar blues progression is built on which three chords?','["I, IV, V","I, II, V","I, III, VI","II, IV, VII"]',0,'The 12-bar blues uses the I, IV, and V chords — the tonic, subdominant, and dominant of the key.','medium'),
('a1111111-0000-0000-0000-000000000012','music','Which composer wrote "The Rite of Spring," which caused a riot at its 1913 premiere?','["Igor Stravinsky","Claude Debussy","Béla Bartók","Sergei Prokofiev"]',0,'Stravinsky''s "The Rite of Spring" premiered in Paris in 1913 and provoked a notorious audience riot due to its radical rhythmic complexity.','medium'),
('a1111111-0000-0000-0000-000000000013','music','What is the term for the gradual slowing of tempo at the end of a piece?','["Accelerando","Ritardando","Fermata","Staccato"]',1,'Ritardando (rit.) means a gradual slowing of tempo, typically used toward the end of a musical phrase or piece.','medium'),
('a1111111-0000-0000-0000-000000000014','music','Which music theorist is associated with the "circle of fifths"?','["Johann David Heinichen","Jean-Philippe Rameau","Heinrich Schenker","Arnold Schoenberg"]',0,'Johann David Heinichen presented an early form of the circle of fifths in 1711 as a compositional aid.','hard'),
('a1111111-0000-0000-0000-000000000015','music','What is "serialism" in 20th-century music?','["Music with no rhythm","A compositional technique using ordered series of pitches","Music played only on strings","A form of musical minimalism"]',1,'Serialism, pioneered by Arnold Schoenberg, organises music around ordered sequences (series) of the 12 chromatic pitches to avoid tonal hierarchy.','hard')
ON CONFLICT (id) DO NOTHING;

-- ---- NEWS (b2222222) ----
INSERT INTO trivia_questions (id, category_id, question, choices, correct_index, explanation, difficulty) VALUES
('b2222222-0000-0000-0000-000000000001','news','What term describes communities sealed off from outside information relying only on self-confirming sources?','["Filter bubble","Epistemic closure","Confirmation bias","Echo chamber"]',1,'Epistemic closure, popularised by Julian Sanchez in 2010, describes a media ecosystem sealed off from outside perspectives — distinct from individual confirmation bias.','medium'),
('b2222222-0000-0000-0000-000000000002','news','According to MIT research, how much faster does false news spread compared to true news on social platforms?','["2 times","4 times","6 times","10 times"]',2,'A 2018 MIT study published in Science found that false news spreads roughly 6 times faster than true news, partly due to its higher emotional novelty.','medium'),
('b2222222-0000-0000-0000-000000000003','news','Who coined the term "attention economy"?','["Marshall McLuhan","Herbert Simon","Neil Postman","Walter Lippmann"]',1,'Psychologist and Nobel laureate Herbert Simon introduced the concept in 1971: in an information-rich world, attention becomes the scarce resource.','hard'),
('b2222222-0000-0000-0000-000000000004','news','What does "solutions journalism" focus on?','["Celebrity news","Evidence-based responses to social problems","Investigative political scandals","Breaking sports news"]',1,'Solutions journalism reports on evidence-based responses to social issues, showing what works, how it works, and the limitations — not just the problem.','easy'),
('b2222222-0000-0000-0000-000000000005','news','What was the name of the landmark U.S. Supreme Court case that established press freedom against prior restraint in 1971?','["New York Times Co. v. United States","Hazelwood v. Kuhlmeier","Near v. Minnesota","Hustler Magazine v. Falwell"]',0,'New York Times Co. v. United States (the "Pentagon Papers" case) ruled the government could not prevent publication of classified documents.','hard'),
('b2222222-0000-0000-0000-000000000006','news','Which journalistic standard requires independently verifying a claim with at least two sources?','["Corroboration","The two-source rule","The pyramid structure","Attribution"]',1,'The two-source rule, associated with Watergate reporting by Woodward and Bernstein, requires that significant claims be confirmed by at least two independent sources.','medium'),
('b2222222-0000-0000-0000-000000000007','news','What is a "lede" in journalism?','["The closing paragraph","The opening sentence or paragraph of a news story","A source who provides background","A photograph caption"]',1,'The lede (also spelled "lead") is the opening of a news article, which must capture the essential facts and hook the reader.','easy'),
('b2222222-0000-0000-0000-000000000008','news','What is the "inverted pyramid" structure in news writing?','["Starting with opinion, ending with facts","Placing the most important information first, then supporting details","A style used only in broadcast journalism","A technique for long-form features"]',1,'The inverted pyramid puts the most newsworthy information at the top, allowing readers to stop reading at any point while still getting the core story.','easy'),
('b2222222-0000-0000-0000-000000000009','news','Which event is credited with launching the era of 24-hour cable news?','["The Gulf War (1991)","The Iran Hostage Crisis (1979)","The Space Shuttle Challenger disaster (1986)","September 11 attacks (2001)"]',0,'CNN''s live, around-the-clock coverage of the Gulf War in 1991 demonstrated the viability of 24-hour news and transformed cable news.','medium'),
('b2222222-0000-0000-0000-000000000010','news','What is "churnalism"?','["Investigative long-form reporting","Repackaging press releases as original journalism","A style of broadcast news","Opinion journalism disguised as reporting"]',1,'Churnalism describes the practice of rewriting press releases and wire copy with minimal verification — driven by newsroom speed and staff cuts.','medium'),
('b2222222-0000-0000-0000-000000000011','news','The Reuters Institute Digital News Report surveys people in how many countries annually?','["12","25","46","80"]',2,'The Reuters Institute Digital News Report covers around 46 countries, making it one of the largest annual surveys of news consumption habits.','hard'),
('b2222222-0000-0000-0000-000000000012','news','What is "access journalism"?','["Reporting from conflict zones","Trading favourable coverage for ongoing source access","Citizen journalism via social media","Hyperlocal community reporting"]',1,'Access journalism describes the practice of softening coverage to maintain relationships with powerful sources who provide exclusive access.','hard'),
('b2222222-0000-0000-0000-000000000013','news','Which term describes the phenomenon of people seeking out only news that confirms their existing beliefs?','["Spiral of silence","Confirmation bias","Agenda setting","Framing effect"]',1,'Confirmation bias leads people to seek, interpret, and recall information in ways that confirm their existing beliefs, shaping news consumption patterns.','easy'),
('b2222222-0000-0000-0000-000000000014','news','Who developed the "agenda-setting" theory of media influence?','["Walter Lippmann","Maxwell McCombs and Donald Shaw","Jürgen Habermas","Edward Herman"]',1,'Maxwell McCombs and Donald Shaw introduced agenda-setting theory in their 1972 study of the 1968 U.S. presidential election: media doesn''t tell us what to think, but what to think about.','hard'),
('b2222222-0000-0000-0000-000000000015','news','What percentage of people globally get some news from social media, according to Reuters Institute 2023 data?','["28%","48%","60%","75%"]',2,'Reuters Institute''s 2023 report found roughly 60% of people across surveyed countries use social media as a news source.','hard')
ON CONFLICT (id) DO NOTHING;

-- ---- HISTORY (c3333333) ----
INSERT INTO trivia_questions (id, category_id, question, choices, correct_index, explanation, difficulty) VALUES
('c3333333-0000-0000-0000-000000000001','history','Which ancient library predated the Library of Alexandria by roughly 400 years?','["Library of Pergamon","Library of Ashurbanipal","Library of Celsus","Library of Alexandria"]',1,'The Library of Ashurbanipal in Nineveh, assembled around 650 BCE, held over 30,000 clay tablets including the Epic of Gilgamesh.','medium'),
('c3333333-0000-0000-0000-000000000002','history','What event in 1815 caused the "Year Without a Summer" in 1816?','["Eruption of Krakatoa","Eruption of Mount Tambora","Eruption of Mount Pinatubo","A series of earthquakes in Japan"]',1,'Mount Tambora''s 1815 eruption was the largest in recorded history; its aerosol cloud lowered global temperatures by 0.4–0.7°C throughout 1816.','medium'),
('c3333333-0000-0000-0000-000000000003','history','The ancient Greek theory of political cycles — monarchy to tyranny to aristocracy to oligarchy to democracy to mob rule — is called what?','["Dialectic","Anacyclosis","Eudaimonia","Stasis"]',1,'Anacyclosis was articulated by the historian Polybius (c. 150 BCE) to describe the recurring degradation of governments.','hard'),
('c3333333-0000-0000-0000-000000000004','history','In what year did the Berlin Wall fall?','["1987","1989","1991","1993"]',1,'The Berlin Wall fell on November 9, 1989, marking the symbolic end of the Cold War division of Germany.','easy'),
('c3333333-0000-0000-0000-000000000005','history','Who was the first Roman Emperor?','["Julius Caesar","Marcus Aurelius","Augustus","Nero"]',2,'Augustus (Octavian) became the first Roman Emperor in 27 BCE after defeating Mark Antony and Cleopatra.','easy'),
('c3333333-0000-0000-0000-000000000006','history','The Black Death of the 14th century was caused by which bacterium?','["Vibrio cholerae","Yersinia pestis","Mycobacterium tuberculosis","Clostridium botulinum"]',1,'Yersinia pestis, transmitted primarily by rat fleas, caused the bubonic plague that killed 30–60% of Europe''s population between 1347 and 1351.','medium'),
('c3333333-0000-0000-0000-000000000007','history','Which treaty ended World War I?','["Treaty of Versailles","Treaty of Brest-Litovsk","Treaty of Paris","Treaty of Utrecht"]',0,'The Treaty of Versailles, signed on June 28, 1919, formally ended WWI and imposed heavy reparations on Germany.','easy'),
('c3333333-0000-0000-0000-000000000008','history','The Magna Carta was signed in which year?','["1066","1215","1348","1492"]',1,'King John of England sealed the Magna Carta at Runnymede on June 15, 1215, establishing limits on royal power.','easy'),
('c3333333-0000-0000-0000-000000000009','history','Who led the Haitian Revolution, resulting in the first free Black republic in 1804?','["Toussaint Louverture","Jean-Jacques Dessalines","Henri Christophe","Alexandre Pétion"]',1,'Jean-Jacques Dessalines declared Haitian independence on January 1, 1804, after Toussaint Louverture''s capture by France.','hard'),
('c3333333-0000-0000-0000-000000000010','history','The Silk Road primarily connected China to which region in the West?','["Sub-Saharan Africa","The Mediterranean and Middle East","Northern Europe","The Americas"]',1,'The Silk Road was a network of trade routes connecting East Asia to the Mediterranean, carrying silk, spices, and ideas over thousands of years.','easy'),
('c3333333-0000-0000-0000-000000000011','history','Which ancient civilisation built Machu Picchu?','["Aztec","Maya","Inca","Olmec"]',2,'Machu Picchu was built by the Inca Empire around 1450 CE and is located in the Andes of present-day Peru.','easy'),
('c3333333-0000-0000-0000-000000000012','history','The 1884–85 Berlin Conference divided Africa among European colonial powers. Which nation hosted it?','["Britain","France","Germany","Belgium"]',2,'The Berlin Conference was hosted by Chancellor Otto von Bismarck of Germany to regulate the European colonisation of Africa.','medium'),
('c3333333-0000-0000-0000-000000000013','history','Which Chinese dynasty built the majority of the Great Wall as it exists today?','["Han Dynasty","Tang Dynasty","Ming Dynasty","Qin Dynasty"]',2,'While the Qin Dynasty built early walls, most of the Great Wall visible today was constructed during the Ming Dynasty (1368–1644).','medium'),
('c3333333-0000-0000-0000-000000000014','history','The Thirty Years'' War (1618–1648) was ended by which peace agreement?','["Peace of Augsburg","Peace of Westphalia","Congress of Vienna","Treaty of Karlowitz"]',1,'The Peace of Westphalia (1648) ended the Thirty Years'' War and established principles of state sovereignty that shaped modern international relations.','hard'),
('c3333333-0000-0000-0000-000000000015','history','Who wrote "The Prince," a foundational text of political realism?','["Erasmus","Thomas More","Niccolò Machiavelli","Francesco Guicciardini"]',2,'Niccolò Machiavelli wrote "The Prince" (c. 1513) as a practical guide for rulers, arguing that effective leadership sometimes requires ruthless pragmatism.','medium')
ON CONFLICT (id) DO NOTHING;

-- ---- SPORTS (d4444444) ----
INSERT INTO trivia_questions (id, category_id, question, choices, correct_index, explanation, difficulty) VALUES
('d4444444-0000-0000-0000-000000000001','sports','Dick Fosbury revolutionised high jump at which Olympic Games?','["1964 Tokyo","1968 Mexico City","1972 Munich","1976 Montreal"]',1,'Dick Fosbury introduced his backward-arching "Fosbury Flop" technique at the 1968 Mexico City Olympics, winning gold and changing the sport forever.','medium'),
('d4444444-0000-0000-0000-000000000002','sports','What is "proprioception" in sports science?','["The ability to predict opponent movements","The body''s sense of its own position and movement without visual input","A technique for sprint starts","A measure of cardiovascular endurance"]',1,'Proprioception is the body''s ability to sense its position, movement, and force in space using mechanoreceptors in muscles, tendons, and joints.','medium'),
('d4444444-0000-0000-0000-000000000003','sports','How many players are on the field for each team in American football?','["10","11","12","9"]',1,'Each American football team has 11 players on the field at a time, on both offense and defense.','easy'),
('d4444444-0000-0000-0000-000000000004','sports','Which country has won the most FIFA World Cup titles?','["Germany","Argentina","Italy","Brazil"]',3,'Brazil has won the FIFA World Cup five times (1958, 1962, 1970, 1994, 2002), more than any other nation.','easy'),
('d4444444-0000-0000-0000-000000000005','sports','What is the diameter of a standard basketball hoop in inches?','["16 inches","18 inches","20 inches","22 inches"]',1,'A standard basketball hoop has an internal diameter of 18 inches, which is just wide enough for the ball (9.4 inch diameter) to pass through.','medium'),
('d4444444-0000-0000-0000-000000000006','sports','The "hot hand" fallacy research was famously reanalysed in 2016. What flaw was found in the original 1985 study?','["The sample size was too small","A statistical bias that suppressed the hot hand signal","The players were not professional","The study used the wrong sport"]',1,'Miller and Sanjurjo (2016) showed the original study had a sampling bias: conditioning on previous makes biases remaining attempts downward, masking the real hot hand effect.','hard'),
('d4444444-0000-0000-0000-000000000007','sports','How long is a standard marathon race?','["26.1 miles","26.2 miles","25.0 miles","26.4 miles"]',1,'A marathon is exactly 26.2 miles (42.195 km), standardised from the 1908 London Olympics distance.','easy'),
('d4444444-0000-0000-0000-000000000008','sports','In tennis, what is the term for a score of 40-40?','["Advantage","Deuce","Break point","Match point"]',1,'Deuce occurs when both players reach 40 points; a player must then win two consecutive points to win the game.','easy'),
('d4444444-0000-0000-0000-000000000009','sports','Which swimmer won 8 gold medals at a single Olympic Games in 2008?','["Ian Thorpe","Ryan Lochte","Michael Phelps","Mark Spitz"]',2,'Michael Phelps won 8 gold medals at the 2008 Beijing Olympics, the most by any athlete at a single Games.','easy'),
('d4444444-0000-0000-0000-000000000010','sports','What does VO2 max measure in athletic performance?','["Maximum sprint speed","Maximum oxygen uptake capacity","Muscle fibre density","Heart rate recovery"]',1,'VO2 max measures the maximum rate at which the body can consume oxygen during intense exercise — a key indicator of aerobic fitness.','medium'),
('d4444444-0000-0000-0000-000000000011','sports','The Fosbury Flop works partly because the athlete''s centre of mass does what?','["Rises above the bar","Passes below the bar while the body goes over it","Stays level with the bar","Stays below the takeoff point"]',1,'In a well-executed Fosbury Flop, each body segment passes over the bar sequentially while the athlete''s centre of mass actually travels below the bar — a physics advantage.','hard'),
('d4444444-0000-0000-0000-000000000012','sports','Which sport uses a "puck" instead of a ball?','["Lacrosse","Water polo","Ice hockey","Polo"]',2,'Ice hockey uses a vulcanised rubber puck; the flat disc shape reduces bouncing on ice surfaces.','easy'),
('d4444444-0000-0000-0000-000000000013','sports','In cricket, how many runs does a batsman score for hitting the ball over the boundary without it bouncing?','["4","5","6","8"]',2,'A six is scored when a batsman hits the ball over the boundary rope without it touching the ground inside the boundary.','medium'),
('d4444444-0000-0000-0000-000000000014','sports','What is "periodisation" in strength and conditioning?','["Training in short daily bursts","Systematic planning of training cycles to peak performance at the right time","A recovery technique using ice baths","A nutritional strategy"]',1,'Periodisation divides training into macrocycles, mesocycles, and microcycles, varying intensity and volume to maximise adaptation and peak at competitions.','hard'),
('d4444444-0000-0000-0000-000000000015','sports','Which country invented the sport of rugby?','["Scotland","Australia","England","New Zealand"]',2,'Rugby originated at Rugby School in England around 1823, reportedly when William Webb Ellis picked up the ball and ran with it during a football match.','medium')
ON CONFLICT (id) DO NOTHING;

-- ---- FINANCE (f5555555) ----
INSERT INTO trivia_questions (id, category_id, question, choices, correct_index, explanation, difficulty) VALUES
('f5555555-0000-0000-0000-000000000001','finance','The Rule of 72 estimates how long it takes to double money. At 8% annual return, how many years does it take?','["7 years","9 years","12 years","6 years"]',1,'72 ÷ 8 = 9 years. The Rule of 72 is an accurate approximation for interest rates between 6% and 10%.','easy'),
('f5555555-0000-0000-0000-000000000002','finance','What does an inverted yield curve typically signal?','["Economic expansion","An approaching recession","Rising inflation","Central bank rate cuts"]',1,'An inverted yield curve — where short-term rates exceed long-term rates — has preceded every U.S. recession since 1955.','medium'),
('f5555555-0000-0000-0000-000000000003','finance','Over 15-year periods, approximately what percentage of actively managed funds underperform their benchmark index?','["50%","70%","90%","30%"]',2,'S&P SPIVA data consistently shows about 90% of actively managed funds underperform their benchmark index net of fees over 15-year periods.','medium'),
('f5555555-0000-0000-0000-000000000004','finance','Who launched the first index fund for retail investors in 1976?','["Warren Buffett","Jack Bogle","Benjamin Graham","George Soros"]',1,'Jack Bogle founded Vanguard and launched the first retail index fund in 1976, initially mocked as "Bogle''s folly."','medium'),
('f5555555-0000-0000-0000-000000000005','finance','What is compound interest?','["Interest calculated only on the principal","Interest earned on both the principal and previously accumulated interest","A fixed rate paid annually","Interest set by the central bank"]',1,'Compound interest means earning interest on both the original principal and previously earned interest — the key driver of long-term wealth growth.','easy'),
('f5555555-0000-0000-0000-000000000006','finance','The Luca Pacioli reference to the Rule of 72 dates to which year?','["1494","1602","1776","1550"]',0,'Luca Pacioli referenced the Rule of 72 in "Summa de arithmetica" in 1494, making it one of the oldest finance heuristics still in common use.','hard'),
('f5555555-0000-0000-0000-000000000007','finance','What is "dollar-cost averaging"?','["Buying only at market lows","Investing a fixed amount at regular intervals regardless of price","Converting investments to cash monthly","Buying stocks only in round-dollar amounts"]',1,'Dollar-cost averaging involves investing a fixed sum at regular intervals, which automatically buys more shares when prices are low and fewer when high.','medium'),
('f5555555-0000-0000-0000-000000000008','finance','What is the "equity risk premium"?','["The fee charged by equity brokers","The extra return investors expect from stocks over risk-free bonds","The tax on capital gains","The dividend yield of an index"]',1,'The equity risk premium is the additional return investors demand for holding risky stocks over safe government bonds — historically around 4–6% per year.','hard'),
('f5555555-0000-0000-0000-000000000009','finance','In accounting, what does P/E ratio stand for?','["Profit-to-Expense ratio","Price-to-Earnings ratio","Principal-to-Equity ratio","Profit-to-Equity ratio"]',1,'The Price-to-Earnings (P/E) ratio measures how much investors pay per dollar of earnings — a fundamental valuation metric.','easy'),
('f5555555-0000-0000-0000-000000000010','finance','What caused the 2008 global financial crisis?','["High oil prices","A collapse in technology stocks","A housing bubble fuelled by subprime mortgage securities","Rising government debt in Europe"]',2,'The 2008 crisis was triggered by the collapse of the U.S. housing market, amplified by complex mortgage-backed securities and excessive leverage in the financial system.','medium'),
('f5555555-0000-0000-0000-000000000011','finance','What is "quantitative easing"?','["Raising interest rates to reduce inflation","A central bank buying assets to inject money into the economy","Reducing government spending","Tightening bank reserve requirements"]',1,'Quantitative easing (QE) involves a central bank purchasing financial assets to increase money supply and stimulate the economy when interest rates are near zero.','medium'),
('f5555555-0000-0000-0000-000000000012','finance','Which economic concept states that in competitive markets, prices reflect all available information?','["Keynesian theory","Efficient Market Hypothesis","Modern Portfolio Theory","Supply-side economics"]',1,'The Efficient Market Hypothesis (EMH), developed by Eugene Fama, argues that asset prices reflect all available information, making it impossible to consistently outperform the market.','hard'),
('f5555555-0000-0000-0000-000000000013','finance','What is "beta" in finance?','["The dividend yield of a stock","A measure of a stock''s volatility relative to the market","The book value of a company","The interest rate on corporate bonds"]',1,'Beta measures a stock''s volatility relative to the overall market: a beta of 1 means it moves with the market; above 1 means more volatile.','medium'),
('f5555555-0000-0000-0000-000000000014','finance','The "wealth effect" describes what phenomenon?','["Higher income leading to more spending","Rising asset prices making people feel wealthier and spend more","Government subsidies boosting consumer confidence","Lower tax rates stimulating investment"]',1,'The wealth effect occurs when rising asset values (homes, stocks) make consumers feel wealthier and more willing to spend, even without a change in actual income.','hard'),
('f5555555-0000-0000-0000-000000000015','finance','What is the "liquidity trap"?','["When banks hoard cash instead of lending","When interest rates are so low that monetary policy loses effectiveness","When markets freeze during a crisis","When currencies become worthless"]',1,'A liquidity trap occurs when interest rates near zero mean that additional money supply fails to stimulate spending — a problem Keynes identified and Japan experienced in the 1990s.','hard')
ON CONFLICT (id) DO NOTHING;

-- ---- SCIENCE (ac666666) ----
INSERT INTO trivia_questions (id, category_id, question, choices, correct_index, explanation, difficulty) VALUES
('ac666666-0000-0000-0000-000000000001','science','CRISPR gene-editing technology uses which protein to cut DNA at targeted locations?','["Helicase","Cas9","Ligase","Polymerase"]',1,'The CRISPR-Cas9 system uses guide RNA to direct the Cas9 protein to a specific DNA sequence, where it makes a precise cut.','medium'),
('ac666666-0000-0000-0000-000000000002','science','What is the Mpemba effect?','["Cold water boils faster than hot water","Hot water can freeze faster than cold water under specific conditions","Ice melts faster in salt water","Steam condenses faster at altitude"]',1,'The Mpemba effect, named after Tanzanian student Erasto Mpemba, describes the counterintuitive observation that hot water can freeze faster than cold water.','medium'),
('ac666666-0000-0000-0000-000000000003','science','The Second Law of Thermodynamics states that entropy in a closed system always does what?','["Decreases over time","Remains constant","Increases over time","Oscillates periodically"]',2,'The Second Law states that total entropy (disorder) in a closed system always increases over time — the universe trends irreversibly toward disorder.','medium'),
('ac666666-0000-0000-0000-000000000004','science','What is the atomic number of carbon?','["4","6","8","12"]',1,'Carbon has atomic number 6, meaning it has 6 protons in its nucleus. It is the basis of all known life on Earth.','easy'),
('ac666666-0000-0000-0000-000000000005','science','Which scientist developed the theory of general relativity?','["Isaac Newton","Niels Bohr","Albert Einstein","Max Planck"]',2,'Albert Einstein published the theory of general relativity in 1915, describing gravity as the curvature of spacetime caused by mass.','easy'),
('ac666666-0000-0000-0000-000000000006','science','What is the speed of light in a vacuum?','["300,000 km/s","150,000 km/s","450,000 km/s","1,080,000 km/h"]',0,'The speed of light in a vacuum is approximately 299,792 km/s (often rounded to 300,000 km/s), denoted as c.','easy'),
('ac666666-0000-0000-0000-000000000007','science','DNA''s double helix structure was described by Watson and Crick using X-ray data from which scientist?','["Linus Pauling","Rosalind Franklin","Erwin Chargaff","Maurice Wilkins"]',1,'Rosalind Franklin''s X-ray diffraction image "Photo 51" was key to Watson and Crick''s 1953 determination of DNA''s double helix structure.','medium'),
('ac666666-0000-0000-0000-000000000008','science','What is the half-life of carbon-14, used in radiocarbon dating?','["1,000 years","5,730 years","14,000 years","50,000 years"]',1,'Carbon-14 has a half-life of approximately 5,730 years, making radiocarbon dating effective for organic material up to about 50,000 years old.','hard'),
('ac666666-0000-0000-0000-000000000009','science','Which particle gives other particles mass according to the Standard Model?','["Photon","Gluon","Higgs boson","W boson"]',2,'The Higgs boson, confirmed at CERN in 2012, is associated with the Higgs field, which gives elementary particles their mass.','medium'),
('ac666666-0000-0000-0000-000000000010','science','What phenomenon explains why the sky is blue?','["Reflection of ocean colour","Rayleigh scattering of sunlight by atmospheric molecules","Absorption of red light by ozone","Refraction by water vapour"]',1,'Rayleigh scattering causes short-wavelength blue light to scatter more than other colours when sunlight hits atmospheric molecules, making the sky appear blue.','medium'),
('ac666666-0000-0000-0000-000000000011','science','Who discovered penicillin?','["Louis Pasteur","Robert Koch","Alexander Fleming","Joseph Lister"]',2,'Alexander Fleming discovered penicillin in 1928 when he noticed that the mould Penicillium notatum was killing bacteria on one of his culture plates.','easy'),
('ac666666-0000-0000-0000-000000000012','science','What is a "control group" in a scientific experiment?','["The group given the treatment","The group receiving no treatment for comparison","The lead researcher''s team","The group that validates results"]',1,'A control group receives no experimental treatment, serving as a baseline to compare against the experimental group and isolate the effect of the variable being tested.','easy'),
('ac666666-0000-0000-0000-000000000013','science','What is the name of the process by which plants convert sunlight into chemical energy?','["Respiration","Chemosynthesis","Photosynthesis","Transpiration"]',2,'Photosynthesis is the process by which plants use sunlight, water, and CO₂ to produce glucose and oxygen in chloroplasts.','easy'),
('ac666666-0000-0000-0000-000000000014','science','Which gas makes up the largest proportion of Earth''s atmosphere?','["Oxygen","Carbon dioxide","Argon","Nitrogen"]',3,'Nitrogen makes up approximately 78% of Earth''s atmosphere, while oxygen accounts for about 21%.','easy'),
('ac666666-0000-0000-0000-000000000015','science','What is "dark matter"?','["Black holes at the centre of galaxies","Matter that absorbs light","Unobserved mass that exerts gravitational effects but does not interact with light","The space between galaxies"]',2,'Dark matter is hypothetical matter that accounts for the extra gravitational effects observed in galaxies — it doesn''t interact with the electromagnetic force and cannot be directly observed.','hard')
ON CONFLICT (id) DO NOTHING;

-- ---- TECHNOLOGY (b7777777) ----
INSERT INTO trivia_questions (id, category_id, question, choices, correct_index, explanation, difficulty) VALUES
('b7777777-0000-0000-0000-000000000001','technology','What does the "Lindy Effect" predict about technology?','["Newer technology always replaces older technology within 10 years","Technology that has survived longer is likely to survive longer still","Technology improves exponentially","All technology becomes obsolete within 50 years"]',1,'The Lindy Effect holds that the future life expectancy of a non-perishable thing scales with its current age — old tech that survived has proven its durability.','medium'),
('b7777777-0000-0000-0000-000000000002','technology','Gordon Moore''s 1965 prediction stated that transistor count would double roughly every how many years?','["1 year","2 years","3 years","5 years"]',1,'Moore''s Law observed that the number of transistors on integrated circuits doubles approximately every two years, driving decades of computing progress.','easy'),
('b7777777-0000-0000-0000-000000000003','technology','Who coined the term "technical debt"?','["Martin Fowler","Linus Torvalds","Ward Cunningham","Kent Beck"]',2,'Ward Cunningham coined "technical debt" in 1992 to describe the cost of shortcuts and deferred maintenance in software systems.','medium'),
('b7777777-0000-0000-0000-000000000004','technology','What does "TCP/IP" stand for?','["Terminal Control Protocol / Internet Protocol","Transmission Control Protocol / Internet Protocol","Transfer Communication Protocol / Internal Protocol","Typed Control Protocol / IP"]',1,'TCP/IP (Transmission Control Protocol / Internet Protocol) is the foundational communication protocol suite of the internet.','medium'),
('b7777777-0000-0000-0000-000000000005','technology','Who is credited with inventing the World Wide Web?','["Vint Cerf","Tim Berners-Lee","Steve Jobs","Marc Andreessen"]',1,'Tim Berners-Lee invented the World Wide Web in 1989 while working at CERN, creating HTTP, HTML, and the first web browser.','easy'),
('b7777777-0000-0000-0000-000000000006','technology','What does "SQL" stand for?','["Sequential Query Language","Structured Query Language","System Query Language","Standard Query Language"]',1,'SQL stands for Structured Query Language, used to manage and query relational databases.','easy'),
('b7777777-0000-0000-0000-000000000007','technology','What is "Moore''s Law"?','["A law of physics governing transistor behaviour","An observation that transistor density doubles roughly every two years","A prediction that software will always outpace hardware","A theorem about network growth"]',1,'Moore''s Law is an empirical observation, not a law of physics — it describes the historical trend of transistor density doubling roughly every two years.','easy'),
('b7777777-0000-0000-0000-000000000008','technology','What is a "hash function" used for in computing?','["Encrypting data so only authorised users can read it","Mapping data of arbitrary size to a fixed-size output","Compressing files for storage","Translating human language to machine code"]',1,'A hash function takes input of any size and returns a fixed-size output (hash), used for data integrity checks, passwords, and data structures like hash tables.','medium'),
('b7777777-0000-0000-0000-000000000009','technology','In machine learning, what is "overfitting"?','["A model that performs well on training data but poorly on new data","A model trained on too little data","A model that learns too slowly","A model with too few parameters"]',0,'Overfitting occurs when a model learns the training data so well (including its noise) that it fails to generalise to new, unseen data.','medium'),
('b7777777-0000-0000-0000-000000000010','technology','What does "open source" software mean?','["Software that costs nothing","Software whose source code is publicly available for inspection and modification","Software developed by governments","Software that works on all operating systems"]',1,'Open source software has its source code publicly available, allowing anyone to inspect, modify, and distribute it under specific license terms.','easy'),
('b7777777-0000-0000-0000-000000000011','technology','What is the purpose of a "firewall" in network security?','["To encrypt data in transit","To monitor and control incoming and outgoing network traffic based on security rules","To detect viruses in files","To speed up network connections"]',1,'A firewall monitors and controls network traffic based on predefined security rules, acting as a barrier between trusted and untrusted networks.','easy'),
('b7777777-0000-0000-0000-000000000012','technology','What is "latency" in computing and networking?','["The maximum data transfer speed","The delay between a request and the start of the response","The number of simultaneous connections","The amount of stored data"]',1,'Latency is the time delay between when a request is made and when the response begins — critical for real-time applications like gaming and video calls.','medium'),
('b7777777-0000-0000-0000-000000000013','technology','Which programming paradigm treats computation as the evaluation of mathematical functions and avoids changing state?','["Object-oriented programming","Procedural programming","Functional programming","Event-driven programming"]',2,'Functional programming treats computation as evaluation of mathematical functions, emphasising immutability and avoidance of side effects.','hard'),
('b7777777-0000-0000-0000-000000000014','technology','What does "API" stand for?','["Application Programming Interface","Applied Programming Integration","Automated Process Interface","Application Protocol Index"]',0,'API (Application Programming Interface) is a set of rules that allows different software applications to communicate with each other.','easy'),
('b7777777-0000-0000-0000-000000000015','technology','What is the name of the vulnerability that allows attackers to inject malicious SQL into a query?','["Cross-site scripting","Buffer overflow","SQL injection","Man-in-the-middle attack"]',2,'SQL injection exploits insufficient input sanitisation to insert malicious SQL commands into a query, potentially giving attackers access to a database.','medium')
ON CONFLICT (id) DO NOTHING;

-- ---- ART (a8888888) ----
INSERT INTO trivia_questions (id, category_id, question, choices, correct_index, explanation, difficulty) VALUES
('a8888888-0000-0000-0000-000000000001','art','What is "chiaroscuro"?','["A style of painting using only primary colours","The use of strong light-dark contrasts to create three-dimensionality","A Japanese printing technique","A form of abstract sculpture"]',1,'Chiaroscuro (Italian: "light-dark") is a technique using strong contrasts between light and shadow to give the illusion of volume, developed by Leonardo and taken to extremes by Caravaggio.','medium'),
('a8888888-0000-0000-0000-000000000002','art','What is "wabi-sabi"?','["A Japanese spice used in cooking","A Japanese aesthetic that finds beauty in imperfection and impermanence","A Korean pottery style","A Chinese calligraphy technique"]',1,'Wabi-sabi is a Japanese aesthetic philosophy centred on accepting imperfection, impermanence, and incompleteness — formalised in the tea ceremony tradition by Sen no Rikyū.','medium'),
('a8888888-0000-0000-0000-000000000003','art','Who painted the Sistine Chapel ceiling?','["Leonardo da Vinci","Raphael","Michelangelo","Titian"]',2,'Michelangelo painted the Sistine Chapel ceiling between 1508 and 1512, commissioned by Pope Julius II.','easy'),
('a8888888-0000-0000-0000-000000000004','art','The art movement characterised by visible brushstrokes and an attempt to capture light accurately was called what?','["Cubism","Surrealism","Impressionism","Expressionism"]',2,'Impressionism, pioneered by Monet, Renoir, and Pissarro in 1870s France, used loose brushwork and attention to light to capture fleeting moments.','easy'),
('a8888888-0000-0000-0000-000000000005','art','What is "tenebrism"?','["An extreme version of chiaroscuro with nearly pitch-black backgrounds","A technique of applying paint with a knife","A method of watercolour painting","A style of minimalist sculpture"]',0,'Tenebrism is an extreme form of chiaroscuro associated with Caravaggio, using near-total darkness with dramatic single-source lighting.','hard'),
('a8888888-0000-0000-0000-000000000006','art','Which artist created "The Persistence of Memory," famous for its melting clocks?','["Pablo Picasso","Salvador Dalí","René Magritte","Max Ernst"]',1,'Salvador Dalí painted "The Persistence of Memory" in 1931; the melting clocks symbolise the fluid, irrational nature of time in dreams.','easy'),
('a8888888-0000-0000-0000-000000000007','art','What is the term for the Japanese art of repairing broken pottery with gold?','["Wabi-sabi","Ikebana","Kintsugi","Origami"]',2,'Kintsugi ("golden joinery") is the practice of repairing cracked pottery with lacquer mixed with gold, treating the breakage as part of the object''s history.','medium'),
('a8888888-0000-0000-0000-000000000008','art','Which art movement was associated with Sigmund Freud''s theories and depicted dreamlike imagery?','["Dadaism","Futurism","Surrealism","Constructivism"]',2,'Surrealism, founded by André Breton in 1924, drew on Freudian ideas to explore the unconscious mind through dreamlike, irrational imagery.','medium'),
('a8888888-0000-0000-0000-000000000009','art','What is the primary binding medium in oil paint?','["Water","Gum arabic","Linseed oil","Egg yolk"]',2,'Oil paints use linseed oil (or other drying oils) as the binding medium, which dries through oxidation rather than evaporation, allowing extended working time.','medium'),
('a8888888-0000-0000-0000-000000000010','art','Which Picasso style broke objects into geometric fragments shown from multiple viewpoints?','["Fauvism","Cubism","Abstract Expressionism","Op Art"]',1,'Cubism, co-developed by Picasso and Braque from around 1907, depicted subjects from multiple simultaneous viewpoints, fragmenting form into geometric planes.','easy'),
('a8888888-0000-0000-0000-000000000011','art','The "Mona Lisa" is believed to depict which historical figure?','["Lucrezia Borgia","Caterina Sforza","Lisa Gherardini","Isabella d''Este"]',2,'Most art historians identify the Mona Lisa''s subject as Lisa Gherardini, wife of Florentine merchant Francesco del Giocondo — hence its Italian name "La Gioconda."','medium'),
('a8888888-0000-0000-0000-000000000012','art','What painting technique involves applying thick paint to create texture?','["Impasto","Sfumato","Grisaille","Scumbling"]',0,'Impasto is a painting technique where paint is applied very thickly, creating a textured, almost sculptural surface — famously used by Van Gogh.','medium'),
('a8888888-0000-0000-0000-000000000013','art','Which artist is known for large colour-field canvases and committed suicide in 1970?','["Franz Kline","Mark Rothko","Barnett Newman","Clyfford Still"]',1,'Mark Rothko, associated with Abstract Expressionism and colour-field painting, died in his studio in 1970.','hard'),
('a8888888-0000-0000-0000-000000000014','art','The term "avant-garde" in art originally comes from which field?','["Architecture","Military terminology","Music theory","Literature"]',1,'Avant-garde (French: "advance guard") is a military term for troops advancing ahead of the main force — adopted in art to describe pioneering, experimental work.','hard'),
('a8888888-0000-0000-0000-000000000015','art','What is "sfumato"?','["A technique for creating mosaic patterns","Leonardo da Vinci''s technique of blending tones without harsh outlines","A style of bold, expressive brushwork","A method of fresco painting"]',1,'Sfumato (Italian: "smoky") is Leonardo da Vinci''s technique of softly blending tones and edges, creating a hazy, atmospheric quality.','hard')
ON CONFLICT (id) DO NOTHING;

-- ---- PSYCHOLOGY (e9999999) ----
INSERT INTO trivia_questions (id, category_id, question, choices, correct_index, explanation, difficulty) VALUES
('e9999999-0000-0000-0000-000000000001','psychology','The "peak-end rule" states that we judge experiences based on what?','["The average of all moments","The peak moment and the ending","The first and last moment only","The most recent moment"]',1,'Research by Kahneman and Frederickson showed we judge experiences by their most intense (peak) moment and how they ended, not by the average.','medium'),
('e9999999-0000-0000-0000-000000000002','psychology','Who coined the term "cognitive dissonance"?','["B.F. Skinner","Leon Festinger","Abraham Maslow","Carl Rogers"]',1,'Leon Festinger coined "cognitive dissonance" in 1957 after studying a doomsday cult whose prophecy failed — members responded by doubling down on belief.','medium'),
('e9999999-0000-0000-0000-000000000003','psychology','What does the Dunning-Kruger effect describe?','["Experts systematically underestimating their ability","People with low competence in a domain overestimating their ability","The tendency to follow authority figures","The effect of mood on memory"]',1,'The Dunning-Kruger effect (Kruger & Dunning, 1999) showed that people with limited knowledge in a domain tend to overestimate their competence due to lack of metacognitive insight.','easy'),
('e9999999-0000-0000-0000-000000000004','psychology','What is "confirmation bias"?','["The tendency to remember negative events better","The tendency to seek, favour, and recall information that confirms existing beliefs","The tendency to trust authority","The effect of priming on perception"]',1,'Confirmation bias is the tendency to search for, interpret, and recall information in a way that confirms one''s pre-existing beliefs.','easy'),
('e9999999-0000-0000-0000-000000000005','psychology','What is the "bystander effect"?','["People perform better when observed","Individuals are less likely to help in emergencies when others are present","Groups make riskier decisions than individuals","Memory improves in familiar environments"]',1,'The bystander effect, studied by Darley and Latané after the Kitty Genovese case, shows that the more bystanders present, the less likely any individual is to help.','medium'),
('e9999999-0000-0000-0000-000000000006','psychology','Maslow''s hierarchy of needs places which need at the very top?','["Safety","Love and belonging","Self-actualisation","Esteem"]',2,'Self-actualisation — realising one''s fullest potential — sits at the apex of Maslow''s 1943 hierarchy of needs.','easy'),
('e9999999-0000-0000-0000-000000000007','psychology','What is "operant conditioning"?','["Learning through association of stimuli","Learning through consequences — rewards and punishments","Learning by observing others","Learning through classical pairing"]',1,'Operant conditioning, developed by B.F. Skinner, is learning in which behaviour is shaped by its consequences — reinforcement increases behaviour, punishment decreases it.','medium'),
('e9999999-0000-0000-0000-000000000008','psychology','The "Stanford Prison Experiment" was conducted by which psychologist?','["Stanley Milgram","Philip Zimbardo","Solomon Asch","Gordon Allport"]',1,'Philip Zimbardo conducted the Stanford Prison Experiment in 1971, in which participants assigned as "guards" quickly became abusive — demonstrating situational power over behaviour.','medium'),
('e9999999-0000-0000-0000-000000000009','psychology','What is "priming" in psychology?','["A technique for improving memory through repetition","Exposure to one stimulus influencing the response to a later stimulus","The first impression effect in social interaction","Training the unconscious mind through affirmations"]',1,'Priming occurs when exposure to a stimulus (word, image, concept) influences responses to later stimuli — often without conscious awareness.','medium'),
('e9999999-0000-0000-0000-000000000010','psychology','Which concept describes the discomfort felt when actions conflict with beliefs?','["Attribution error","Cognitive dissonance","Reactance","Self-perception theory"]',1,'Cognitive dissonance (Festinger, 1957) is the psychological discomfort of holding contradictory beliefs or acting against one''s values.','easy'),
('e9999999-0000-0000-0000-000000000011','psychology','What is the "halo effect"?','["The tendency to assume experts are always correct","The tendency to let one positive trait influence overall judgement of a person","The effect of positive emotions on creativity","The tendency to help attractive people more"]',1,'The halo effect describes how one positive characteristic (e.g. attractiveness) biases overall perception of a person in a favourable direction.','medium'),
('e9999999-0000-0000-0000-000000000012','psychology','In classical conditioning, what is the "unconditioned stimulus"?','["A stimulus that only triggers a response after training","A stimulus that naturally and automatically triggers a response","A neutral stimulus","A response that occurs without training"]',1,'The unconditioned stimulus (US) naturally elicits a response without prior learning — e.g., food causing salivation in Pavlov''s experiments.','medium'),
('e9999999-0000-0000-0000-000000000013','psychology','What is "social loafing"?','["Increasing effort when working in groups","The tendency to exert less effort when working collectively than individually","Conforming to group norms","The groupthink phenomenon"]',1,'Social loafing, studied by Ringelmann, is the tendency for individuals to put in less effort when working as part of a group than when working alone.','medium'),
('e9999999-0000-0000-0000-000000000014','psychology','The "fundamental attribution error" refers to what tendency?','["Underestimating situational factors and overestimating personality factors in others'' behaviour","Overestimating the role of luck in success","Underestimating one''s own capabilities","Attributing all events to external causes"]',0,'The fundamental attribution error is the tendency to overattribute others'' behaviour to their character (dispositional factors) while underestimating situational influences.','hard'),
('e9999999-0000-0000-0000-000000000015','psychology','What is "neuroplasticity"?','["The brain''s fixed structure from birth","The brain''s ability to reorganise itself by forming new neural connections throughout life","The process of neuron death in ageing","The speed at which neurons fire"]',1,'Neuroplasticity is the brain''s ability to change its structure and function in response to experience, learning, and injury — it continues throughout life, not just in childhood.','medium')
ON CONFLICT (id) DO NOTHING;

-- ---- SPACE (ea101010) ----
INSERT INTO trivia_questions (id, category_id, question, choices, correct_index, explanation, difficulty) VALUES
('ea101010-0000-0000-0000-000000000001','space','Which space telescope, launched in 2021, orbits the Sun-Earth L2 Lagrange point?','["Hubble Space Telescope","Spitzer Space Telescope","James Webb Space Telescope","Chandra X-ray Observatory"]',2,'The James Webb Space Telescope launched in December 2021 and orbits the L2 Lagrange point 1.5 million km from Earth, allowing it to observe in infrared.','easy'),
('ea101010-0000-0000-0000-000000000002','space','What is the Fermi Paradox?','["The contradiction between fast particle decay and the age of the universe","The conflict between the universe''s apparent age and its observed expansion","The contradiction between the high probability of extraterrestrial life and the lack of evidence for it","The impossibility of faster-than-light travel"]',2,'The Fermi Paradox asks: given the universe''s age, size, and the prevalence of Earth-like planets, why have we detected no signs of intelligent extraterrestrial life?','medium'),
('ea101010-0000-0000-0000-000000000003','space','A Lagrange point is a location in space where what condition exists?','["Gravity is zero","The gravitational forces of two large bodies and orbital centrifugal force balance","Light cannot escape","Cosmic radiation is at maximum"]',1,'At Lagrange points, the gravitational pull of two massive bodies (like the Sun and Earth) and the centrifugal force of orbital motion perfectly balance.','medium'),
('ea101010-0000-0000-0000-000000000004','space','What is a light-year?','["The age of a star in years","The distance light travels in one year","The time for light to cross a galaxy","The brightness of a star at 10 parsecs"]',1,'A light-year is the distance light travels in one year in a vacuum — approximately 9.46 × 10¹² kilometres.','easy'),
('ea101010-0000-0000-0000-000000000005','space','What causes a star to eventually expand into a red giant?','["Collision with another star","Depletion of hydrogen fuel in its core","Absorption of surrounding planets","Increase in gravity from dark matter"]',1,'When a star exhausts the hydrogen in its core, fusion stops there, the core contracts, and the outer layers expand enormously, forming a red giant.','medium'),
('ea101010-0000-0000-0000-000000000006','space','How many moons does Mars have?','["0","1","2","4"]',2,'Mars has two small moons — Phobos and Deimos — both thought to be captured asteroids.','easy'),
('ea101010-0000-0000-0000-000000000007','space','What is a "neutron star"?','["A star made entirely of dark matter","The extremely dense remnant of a massive star after a supernova","A star before it ignites nuclear fusion","A star with no magnetic field"]',1,'A neutron star forms when a massive star explodes as a supernova and the core collapses into an incredibly dense object composed almost entirely of neutrons.','medium'),
('ea101010-0000-0000-0000-000000000008','space','The observable universe is approximately how many light-years in diameter?','["4.3 light-years","100,000 light-years","93 billion light-years","1 million light-years"]',2,'The observable universe has a diameter of approximately 93 billion light-years, despite being only 13.8 billion years old due to the expansion of space.','hard'),
('ea101010-0000-0000-0000-000000000009','space','What is the "Great Filter" in discussions of the Fermi Paradox?','["A zone of space where signals cannot travel","A hypothetical barrier that explains why we see no evidence of advanced civilisations","A telescope filter for observing distant galaxies","The limit of human perception of space"]',1,'The Great Filter hypothesis suggests there is a step in the development of life or civilisation that is extremely difficult to pass — either in our past or ahead of us.','hard'),
('ea101010-0000-0000-0000-000000000010','space','Which planet has the largest storm in the solar system?','["Saturn","Neptune","Uranus","Jupiter"]',3,'Jupiter''s Great Red Spot is a persistent anticyclonic storm larger than Earth that has raged for at least 350 years.','easy'),
('ea101010-0000-0000-0000-000000000011','space','What force is responsible for keeping planets in orbit around the Sun?','["Electromagnetic force","Strong nuclear force","Gravity","Centrifugal force"]',2,'Gravity is the attractive force between masses; the Sun''s gravity combined with a planet''s orbital velocity keeps it in a stable elliptical orbit.','easy'),
('ea101010-0000-0000-0000-000000000012','space','What is the "cosmic microwave background"?','["Radiation from active galactic nuclei","Residual thermal radiation from the Big Bang","Light from the first stars","Radiation emitted by pulsars"]',1,'The cosmic microwave background (CMB) is thermal radiation left over from the early universe, approximately 380,000 years after the Big Bang, and provides a snapshot of the early cosmos.','hard'),
('ea101010-0000-0000-0000-000000000013','space','Which planet rotates on its side with an axial tilt of about 98 degrees?','["Neptune","Saturn","Uranus","Venus"]',2,'Uranus has an extreme axial tilt of about 97.77°, meaning it essentially rotates on its side — possibly caused by a massive ancient collision.','medium'),
('ea101010-0000-0000-0000-000000000014','space','What is the approximate mass of the Sun compared to all planets in the solar system combined?','["Equal","10 times more","100 times more","700 times more"]',3,'The Sun contains about 99.86% of the total mass of the solar system — roughly 700 times more than all planets combined.','hard'),
('ea101010-0000-0000-0000-000000000015','space','What type of object did the Event Horizon Telescope photograph in 2019, creating the first image of its kind?','["Neutron star","White dwarf","Black hole","Pulsar"]',2,'In April 2019, the Event Horizon Telescope collaboration released the first direct image of a black hole — the supermassive one at the centre of galaxy M87.','medium')
ON CONFLICT (id) DO NOTHING;

-- ---- LANGUAGE (b1212121) ----
INSERT INTO trivia_questions (id, category_id, question, choices, correct_index, explanation, difficulty) VALUES
('b1212121-0000-0000-0000-000000000001','language','The Great Vowel Shift in English occurred between approximately which years?','["800–1000","1200–1400","1400–1700","1700–1900"]',2,'The Great Vowel Shift occurred between about 1400 and 1700, systematically raising the pronunciation of English long vowels and explaining the divergence between spelling and pronunciation.','medium'),
('b1212121-0000-0000-0000-000000000002','language','What is a "phoneme"?','["A letter of the alphabet","The smallest unit of sound that distinguishes meaning in a language","A grammatical unit","A unit of written language"]',1,'A phoneme is the smallest sound unit in a language that can distinguish one word from another — e.g., changing the initial phoneme in "bat" to /p/ gives "pat."','medium'),
('b1212121-0000-0000-0000-000000000003','language','The Sapir-Whorf hypothesis proposes that language does what?','["Evolves independently of culture","Influences or shapes thought and perception","Is universal across all cultures","Determines intelligence"]',1,'The Sapir-Whorf hypothesis (in its weak form) proposes that language influences thought and perception — best supported by evidence from colour discrimination experiments.','medium'),
('b1212121-0000-0000-0000-000000000004','language','Approximately how many languages are spoken in the world today?','["1,000","3,500","7,000","15,000"]',2,'Linguists estimate there are approximately 7,000 living languages worldwide, though many are endangered and spoken by very few people.','easy'),
('b1212121-0000-0000-0000-000000000005','language','Which language family includes English, German, and Hindi?','["Sino-Tibetan","Afro-Asiatic","Niger-Congo","Indo-European"]',3,'English, German, Hindi, Russian, and Spanish all belong to the Indo-European language family — the most widely spoken family in the world.','easy'),
('b1212121-0000-0000-0000-000000000006','language','What does it mean that Japanese lacks distinct phonemes for /r/ and /l/?','["Japanese cannot express these sounds at all","Adult Japanese speakers have difficulty hearing the /r/ vs /l/ distinction used in English","Japanese uses both sounds interchangeably","Japanese uses a different written symbol for each"]',1,'Because Japanese maps both to a single phoneme, native Japanese speakers have difficulty perceiving the /r/-/l/ distinction critical in English — a neural category never formed.','hard'),
('b1212121-0000-0000-0000-000000000007','language','What is a "lingua franca"?','["The original language of France","A language used as a common medium of communication between people with different native languages","A dying language","A language with no written form"]',1,'A lingua franca is any language used as a bridge between speakers of different native languages — English currently serves as the primary global lingua franca.','easy'),
('b1212121-0000-0000-0000-000000000008','language','Which writing system uses symbols representing syllables rather than individual sounds?','["Alphabet","Syllabary","Logographic","Abjad"]',1,'A syllabary uses symbols representing syllables — Japanese kana (hiragana and katakana) are well-known examples.','medium'),
('b1212121-0000-0000-0000-000000000009','language','What is "code-switching"?','["Encrypting messages for privacy","Alternating between two or more languages in a single conversation","Translating directly between two languages","Using formal language in informal settings"]',1,'Code-switching is the practice of alternating between languages (or dialects) within a single conversation or utterance, common in multilingual communities.','medium'),
('b1212121-0000-0000-0000-000000000010','language','The Rosetta Stone was crucial to deciphering which ancient script?','["Sumerian cuneiform","Linear B","Egyptian hieroglyphics","Mayan glyphs"]',2,'The Rosetta Stone (196 BCE) contained the same decree in three scripts — hieroglyphics, Demotic, and Greek — allowing scholars to decode Egyptian hieroglyphics.','easy'),
('b1212121-0000-0000-0000-000000000011','language','Which language has the largest number of native speakers in the world?','["English","Spanish","Mandarin Chinese","Hindi"]',2,'Mandarin Chinese has the most native speakers of any language, with approximately 920 million native speakers.','easy'),
('b1212121-0000-0000-0000-000000000012','language','What is "semantic drift"?','["The visual change in written language over time","The process by which word meanings change over time","Words borrowed from other languages","The extinction of vocabulary"]',1,'Semantic drift (or semantic change) describes how the meaning of words shifts over time — e.g., "awful" once meant "inspiring awe" and now means "terrible."','medium'),
('b1212121-0000-0000-0000-000000000013','language','Chomsky''s "universal grammar" theory proposes what?','["All languages share the same vocabulary","Humans are born with an innate capacity for language acquisition","Language must be taught explicitly","Grammar is purely a cultural construction"]',1,'Noam Chomsky proposed that humans possess an innate Language Acquisition Device with universal grammar principles, explaining how children acquire language so rapidly.','hard'),
('b1212121-0000-0000-0000-000000000014','language','What percentage of the world''s languages are estimated to be endangered?','["5%","20%","40%","70%"]',2,'Linguists estimate roughly 40% of the world''s languages are endangered, with many having fewer than 1,000 speakers.','hard'),
('b1212121-0000-0000-0000-000000000015','language','The Pirahã language of the Amazon is notable for which unusual feature?','["It has no verbs","It has no colour terms or fixed number words","It uses only two phonemes","It has no grammar rules"]',1,'The Pirahã language lacks fixed number words, colour terms beyond light and dark, and has no perfect tense — used to support arguments about language and cognition.','hard')
ON CONFLICT (id) DO NOTHING;

-- ---- NATURE (ca131313) ----
INSERT INTO trivia_questions (id, category_id, question, choices, correct_index, explanation, difficulty) VALUES
('ca131313-0000-0000-0000-000000000001','nature','What is the "wood wide web"?','["A network of fallen trees","Underground mycorrhizal fungal networks connecting trees","Internet infrastructure built through forests","A type of spider web found in forests"]',1,'The "wood wide web" describes the underground mycorrhizal fungal networks through which trees exchange nutrients, water, and chemical signals.','easy'),
('ca131313-0000-0000-0000-000000000002','nature','Tardigrades survive extreme conditions through a process called what?','["Hibernation","Cryptobiosis","Aestivation","Torpor"]',1,'Cryptobiosis allows tardigrades to suspend all metabolic activity, expelling water and entering a "tun" state that can withstand extreme radiation, temperature, and even the vacuum of space.','medium'),
('ca131313-0000-0000-0000-000000000003','nature','What is "biomimicry"?','["Breeding animals in captivity","Design innovation inspired by solutions found in nature","Genetic modification of crops","The study of fossils"]',1,'Biomimicry applies nature''s 3.8-billion-year-old solutions to human design challenges — examples include Velcro (burdock burrs) and bullet train nose design (kingfisher beak).','easy'),
('ca131313-0000-0000-0000-000000000004','nature','How do plants primarily move water from roots to leaves?','["By pumping it with cellular motors","Through transpiration creating negative pressure that pulls water upward","By diffusion through plant cells","By converting water to gas and reconverting it"]',1,'Transpiration creates a negative pressure (tension) in the xylem that pulls water upward from roots — part of the cohesion-tension mechanism.','hard'),
('ca131313-0000-0000-0000-000000000005','nature','What percentage of Earth''s species live in the ocean?','["20%","50%","70%","94%"]',3,'Scientists estimate approximately 94% of Earth''s living species reside in the ocean, most of which remain undiscovered.','hard'),
('ca131313-0000-0000-0000-000000000006','nature','Which gas do plants absorb during photosynthesis?','["Oxygen","Nitrogen","Carbon dioxide","Hydrogen"]',2,'Plants absorb carbon dioxide (CO₂) during photosynthesis and release oxygen as a byproduct.','easy'),
('ca131313-0000-0000-0000-000000000007','nature','What is the largest living organism on Earth by area?','["Blue whale","Giant sequoia","Honey fungus (Armillaria ostoyae)","Great Barrier Reef"]',2,'A single Armillaria ostoyae honey fungus in Oregon''s Malheur National Forest spans approximately 2,385 acres, making it the largest known living organism.','hard'),
('ca131313-0000-0000-0000-000000000008','nature','What is a "keystone species"?','["The most numerous species in an ecosystem","A species whose impact on its ecosystem is disproportionately large relative to its abundance","The oldest species in an ecosystem","A species that only lives at the top of food chains"]',1,'A keystone species has an outsized effect on its ecosystem relative to its numbers — the sea otter maintains kelp forests by controlling sea urchin populations.','medium'),
('ca131313-0000-0000-0000-000000000009','nature','What is the process by which nitrogen is converted into a form usable by plants?','["Carbon fixation","Nitrogen fixation","Denitrification","Eutrophication"]',1,'Nitrogen fixation converts atmospheric N₂ into ammonia (NH₃) — performed by bacteria like Rhizobium in legume root nodules, making nitrogen available to plants.','medium'),
('ca131313-0000-0000-0000-000000000010','nature','Why are coral reefs called the "rainforests of the sea"?','["They grow only in rainforest climates","Despite covering less than 1% of the ocean floor, they support 25% of all marine species","They absorb as much CO₂ as rainforests","They are found only near coastlines"]',1,'Coral reefs cover less than 1% of the ocean floor but support approximately 25% of all known marine species — making them one of Earth''s most biodiverse ecosystems.','medium'),
('ca131313-0000-0000-0000-000000000011','nature','What is "phenology"?','["The study of animal sounds","The study of cyclic and seasonal natural phenomena, like migration and flowering times","The study of plant genetics","The study of geological time periods"]',1,'Phenology is the study of cyclic biological events — like bird migration, insect emergence, and plant flowering — and their relationship to climate and season.','hard'),
('ca131313-0000-0000-0000-000000000012','nature','The Amazon rainforest produces approximately what fraction of the world''s oxygen?','["1/10","1/4","1/5","1/2"]',2,'The Amazon is often called the "lungs of the Earth" because it produces approximately 20% (one-fifth) of the world''s oxygen through photosynthesis.','medium'),
('ca131313-0000-0000-0000-000000000013','nature','Which animal has the longest migration of any known mammal?','["Gray whale","Humpback whale","Bowhead whale","Minke whale"]',0,'Gray whales migrate up to 14,000 miles round-trip between Arctic feeding grounds and Mexican breeding lagoons — the longest known migration of any mammal.','hard'),
('ca131313-0000-0000-0000-000000000014','nature','What is the primary cause of ocean acidification?','["Oil spills","Absorption of excess atmospheric CO₂","Agricultural fertiliser runoff","Underwater volcanic activity"]',1,'The ocean absorbs about 30% of atmospheric CO₂, which reacts with seawater to form carbonic acid, gradually lowering ocean pH and threatening shellfish and coral.','medium'),
('ca131313-0000-0000-0000-000000000015','nature','What phenomenon causes male fireflies to synchronise their flashes?','["Magnetic field alignment","Coupled oscillator dynamics — each firefly adjusts its rhythm to its neighbours","Response to a dominant female","Reaction to ambient light levels"]',1,'Synchronous firefly flashing is a coupled oscillator phenomenon: each firefly adjusts its timing based on neighbours, causing the whole population to synchronise spontaneously.','hard')
ON CONFLICT (id) DO NOTHING;

-- ---- FOOD (f0141414) ----
INSERT INTO trivia_questions (id, category_id, question, choices, correct_index, explanation, difficulty) VALUES
('f0141414-0000-0000-0000-000000000001','food','Who discovered and named umami, the fifth basic taste?','["Auguste Escoffier","Kikunae Ikeda","René Redzepi","Ferran Adrià"]',1,'Japanese chemist Kikunae Ikeda isolated glutamate from kombu seaweed in 1908 and named the distinct savory taste "umami" (delicious flavour).','medium'),
('f0141414-0000-0000-0000-000000000002','food','What is the "expensive tissue hypothesis" in the context of human evolution?','["Cooking evolved to make food taste better","Cooking freed up energy from digestion, enabling smaller guts and larger brains","Protein-rich diets drove bipedalism","Agriculture enabled larger societies"]',1,'Richard Wrangham argues that cooking, by making calories more bioavailable, allowed the evolution of smaller digestive tracts and larger brains in Homo erectus.','hard'),
('f0141414-0000-0000-0000-000000000003','food','What is "terroir"?','["A French cooking technique","The complete natural environment that gives a food or wine its unique character","A type of French cheese","The practice of pairing food with wine"]',1,'Terroir encompasses soil, topography, climate, and local microorganisms — the full environmental context that makes champagne from Champagne irreplicable elsewhere.','medium'),
('f0141414-0000-0000-0000-000000000004','food','The Maillard reaction, responsible for the browning of cooked meat, requires what two types of molecules?','["Fats and water","Amino acids and reducing sugars","Proteins and salt","Carbohydrates and oxygen"]',1,'The Maillard reaction is a chemical reaction between amino acids and reducing sugars at high heat, creating the hundreds of flavour compounds responsible for browned, roasted flavour.','hard'),
('f0141414-0000-0000-0000-000000000005','food','Which country produces the most coffee in the world?','["Colombia","Ethiopia","Vietnam","Brazil"]',3,'Brazil is the world''s largest coffee producer, accounting for about 35–40% of global coffee production — a position it has held for over 150 years.','easy'),
('f0141414-0000-0000-0000-000000000006','food','What fermentation process makes sourdough bread rise?','["Commercial yeast fermentation","Wild yeast and bacterial (lactic acid) fermentation","Baking powder reaction","Egg protein aeration"]',1,'Sourdough rises through wild yeast (primarily Saccharomyces) and lactic acid bacteria in the starter culture — the same bacteria that produce its characteristic tang.','medium'),
('f0141414-0000-0000-0000-000000000007','food','What is MSG?','["A synthetic flavour enhancer with no natural equivalent","Monosodium glutamate — the purified salt form of glutamate, a naturally occurring amino acid","A type of artificial sweetener","A preservative derived from petroleum"]',1,'Monosodium glutamate (MSG) is the sodium salt of glutamic acid, a naturally occurring amino acid found in tomatoes, parmesan, and soy sauce — it activates umami taste receptors.','medium'),
('f0141414-0000-0000-0000-000000000008','food','What is the Scoville scale used to measure?','["Wine acidity","The pungency (heat) of chilli peppers","The sugar content of fruits","Coffee bitterness"]',1,'The Scoville scale measures the capsaicin content of chilli peppers — the higher the Scoville Heat Units (SHU), the hotter the pepper.','easy'),
('f0141414-0000-0000-0000-000000000009','food','Which country is credited with inventing sushi?','["China","South Korea","Japan","Thailand"]',2,'Sushi originated in Japan, evolving from a Southeast Asian method of preserving fish in fermented rice before becoming the fresh-fish-on-rice dish known today.','easy'),
('f0141414-0000-0000-0000-000000000010','food','What is the primary purpose of blanching vegetables before freezing?','["To add colour","To deactivate enzymes that cause deterioration during freezing","To remove pesticides","To increase nutrient content"]',1,'Blanching (briefly boiling then cooling) deactivates enzymes that continue to degrade texture, colour, and flavour in frozen vegetables.','medium'),
('f0141414-0000-0000-0000-000000000011','food','The "French paradox" refers to what phenomenon?','["French cuisine using more butter than any other","Low rates of cardiovascular disease in France despite high saturated fat consumption","French wine being healthier than other wines","French people eating less overall than other Europeans"]',1,'The French paradox describes the low incidence of heart disease in France despite a diet rich in saturated fats — debated explanations include red wine consumption and smaller portions.','medium'),
('f0141414-0000-0000-0000-000000000012','food','What gives chilli peppers their heat sensation?','["Piperine","Allicin","Capsaicin","Cinnamaldehyde"]',2,'Capsaicin binds to TRPV1 receptors (heat pain receptors) in the mouth, triggering a burning sensation — the same receptors activated by high temperatures.','medium'),
('f0141414-0000-0000-0000-000000000013','food','Which nation consumes the most chocolate per capita?','["Belgium","Switzerland","United States","Germany"]',1,'Switzerland consistently leads in chocolate consumption per capita, at around 10 kg per person per year.','medium'),
('f0141414-0000-0000-0000-000000000014','food','What is "fermentation"?','["Cooking food at very low temperatures","The breakdown of organic substances by microorganisms, producing acids, gases, or alcohol","Preserving food in salt","A high-heat cooking method"]',1,'Fermentation is the metabolic process by which microorganisms (bacteria, yeast, fungi) convert sugars into acids, gases, or alcohol — the basis of bread, yogurt, cheese, wine, and beer.','easy'),
('f0141414-0000-0000-0000-000000000015','food','What culinary technique involves cooking food in a vacuum-sealed bag in precisely temperature-controlled water?','["Confit","Poaching","Sous vide","Braising"]',2,'Sous vide (French: "under vacuum") cooks food sealed in bags in a precisely controlled water bath, enabling consistent results impossible with conventional methods.','medium')
ON CONFLICT (id) DO NOTHING;

-- ---- PHILOSOPHY (eb151515) ----
INSERT INTO trivia_questions (id, category_id, question, choices, correct_index, explanation, difficulty) VALUES
('eb151515-0000-0000-0000-000000000001','philosophy','Epictetus identified the central Stoic practice as what?','["Achieving happiness through pleasure","Distinguishing what is within our control from what is not","Pursuing virtue through civic engagement","Accepting fate without resistance"]',1,'Epictetus, born a slave, argued the core of Stoic practice is distinguishing what is "up to us" (judgements, impulses) from what is not (body, reputation, external events).','medium'),
('eb151515-0000-0000-0000-000000000002','philosophy','The Ship of Theseus thought experiment raises questions about what philosophical topic?','["Free will","The nature of time","Personal identity and continuity","The existence of God"]',2,'The Ship of Theseus asks: if every plank of the ship is replaced, is it the same ship? Applied to persons, it explores what makes someone the same individual over time.','medium'),
('eb151515-0000-0000-0000-000000000003','philosophy','What is "phenomenology"?','["The study of natural phenomena through science","A philosophical method studying the structure of conscious experience from the first-person perspective","A theory of knowledge based only on observable facts","A branch of logic"]',1,'Phenomenology, founded by Edmund Husserl, brackets assumptions about external reality to examine the structure of experience as it is actually lived.','hard'),
('eb151515-0000-0000-0000-000000000004','philosophy','Kant''s categorical imperative states you should act only according to principles that you could will to become what?','["A personal virtue","A natural law","A universal law for all rational beings","An agreed social contract"]',2,'Kant''s categorical imperative: "Act only according to that maxim whereby you can at the same time will that it should become a universal law."','hard'),
('eb151515-0000-0000-0000-000000000005','philosophy','What is Plato''s "Allegory of the Cave" meant to illustrate?','["The dangers of imprisonment","The difference between perceived reality and true forms of knowledge","The importance of education","The nature of democratic government"]',1,'Plato''s Allegory of the Cave depicts prisoners mistaking shadows for reality — illustrating how most people mistake the sensory world for true knowledge of the Forms.','medium'),
('eb151515-0000-0000-0000-000000000006','philosophy','Who said "I think, therefore I am" (Cogito, ergo sum)?','["John Locke","Immanuel Kant","René Descartes","David Hume"]',2,'René Descartes, in "Meditations on First Philosophy" (1641), used this statement to establish the one thing he could not doubt: that a thinking thing must exist.','easy'),
('eb151515-0000-0000-0000-000000000007','philosophy','What is "utilitarianism"?','["The ethical theory that actions are right if they maximise overall well-being or happiness","The view that morality is determined by social norms","The belief that one''s duty determines right action","The view that all moral claims are relative"]',0,'Utilitarianism, developed by Jeremy Bentham and John Stuart Mill, judges actions by their consequences — specifically whether they maximise overall happiness or welfare.','medium'),
('eb151515-0000-0000-0000-000000000008','philosophy','What is the "trolley problem"?','["A paradox about trains and time travel","A thought experiment pitting direct harm against allowing harm to explore moral intuitions","A puzzle about free will and determinism","An argument for utilitarian ethics"]',1,'The trolley problem (Philippa Foot, 1967) asks whether it is permissible to divert a runaway trolley to kill one person instead of five — used to explore consequentialist vs. deontological intuitions.','medium'),
('eb151515-0000-0000-0000-000000000009','philosophy','Nietzsche''s concept of the "will to power" describes what?','["The desire for political control","A fundamental drive toward growth, creativity, and mastery of one''s environment","The will to dominate others","The drive to survive at all costs"]',1,'Nietzsche''s will to power is not merely a desire for domination but a drive for self-overcoming, creativity, and the expression of one''s fullest capacities.','hard'),
('eb151515-0000-0000-0000-000000000010','philosophy','What is "epistemic humility"?','["Refusing to express opinions","Acknowledging the limits of one''s own knowledge and the possibility of being wrong","Being modest about academic credentials","Avoiding philosophical debate"]',1,'Epistemic humility is the intellectual virtue of recognising the limits of one''s own knowledge — essential to rational inquiry and open discourse.','medium'),
('eb151515-0000-0000-0000-000000000011','philosophy','Aristotle''s concept of "eudaimonia" is best translated as what?','["Pleasure","Duty","Flourishing or living well","Virtue"]',2,'Eudaimonia, central to Aristotle''s ethics, is often translated as "happiness" but more precisely means human flourishing — living and doing well in accordance with one''s nature and virtues.','medium'),
('eb151515-0000-0000-0000-000000000012','philosophy','What does "ontology" study?','["The theory of knowledge","The nature of being and existence","The study of moral values","The logic of language"]',1,'Ontology is the branch of metaphysics concerned with the nature of being, existence, and reality — asking questions like "What kinds of things exist?"','medium'),
('eb151515-0000-0000-0000-000000000013','philosophy','The philosophical position that the mind and body are fundamentally different substances was advanced by whom?','["John Locke","Baruch Spinoza","René Descartes","Thomas Hobbes"]',2,'Descartes''s substance dualism held that mind (res cogitans) and matter (res extensa) are two fundamentally distinct substances — creating the "mind-body problem."','hard'),
('eb151515-0000-0000-0000-000000000014','philosophy','What is "Occam''s Razor"?','["The principle that the simplest explanation consistent with evidence is preferred","The rule that all philosophical claims need empirical proof","The idea that ethics must be based on reason alone","The argument that God''s existence cannot be disproved"]',0,'Occam''s Razor (William of Ockham, 14th c.) states that among competing hypotheses, the one with the fewest assumptions should be preferred — "entities should not be multiplied beyond necessity."','medium'),
('eb151515-0000-0000-0000-000000000015','philosophy','What is the "problem of evil" in philosophy of religion?','["The difficulty of defining evil objectively","The argument that an omnipotent, omnibenevolent God''s existence is incompatible with the existence of evil","The study of evil in human history","The question of whether evil is innate or learned"]',1,'The problem of evil argues: if God is all-powerful, all-knowing, and all-good, evil and suffering should not exist — yet they do, challenging theistic belief.','hard')
ON CONFLICT (id) DO NOTHING;

-- ---- CULTURE (cb161616) ----
INSERT INTO trivia_questions (id, category_id, question, choices, correct_index, explanation, difficulty) VALUES
('cb161616-0000-0000-0000-000000000001','culture','The concept of "soft power" in international relations was introduced by which scholar?','["Henry Kissinger","Samuel Huntington","Joseph Nye","Francis Fukuyama"]',2,'Joseph Nye introduced "soft power" in 1990 to describe a nation''s ability to influence others through cultural attraction and values rather than coercion or payment.','hard'),
('cb161616-0000-0000-0000-000000000002','culture','The seven-day week traces back to which ancient civilisation?','["Ancient Egypt","Ancient Greece","Ancient Babylon","Ancient China"]',2,'The Babylonians organised their calendar around the seven celestial bodies visible to the naked eye, creating the seven-day week adopted via Jewish and Roman traditions.','medium'),
('cb161616-0000-0000-0000-000000000003','culture','Anthropologist Edward Hall distinguished "monochronic" and "polychronic" cultures based on what?','["Religious beliefs","Attitudes toward time and scheduling","Food customs","Political systems"]',1,'Edward Hall''s distinction describes cultures that schedule one task at a time (monochronic, e.g. northern Europe) versus cultures that handle multiple simultaneous relationships (polychronic, e.g. Mediterranean).','medium'),
('cb161616-0000-0000-0000-000000000004','culture','What is "cultural relativism"?','["The belief that all cultures are equal in quality","The practice of understanding cultural practices within their own cultural context, not judging them by external standards","The spread of Western culture globally","The study of cultural evolution"]',1,'Cultural relativism is the principle that a person''s beliefs and practices should be understood within their own cultural context, rather than judged by the standards of another culture.','medium'),
('cb161616-0000-0000-0000-000000000005','culture','The "Hallyu" (Korean Wave) refers to what?','["A traditional Korean martial art","The global spread of South Korean popular culture","A Korean economic policy","A style of Korean architecture"]',1,'Hallyu (Korean Wave) refers to the worldwide spread of South Korean pop culture — K-pop, K-drama, K-beauty — that South Korea actively cultivated after the 1997 financial crisis.','easy'),
('cb161616-0000-0000-0000-000000000006','culture','What is "cultural capital" according to sociologist Pierre Bourdieu?','["Monetary investment in cultural institutions","Non-financial social assets — knowledge, skills, tastes — that give social advantage","The economic value of creative industries","Artwork held as financial investment"]',1,'Pierre Bourdieu defined cultural capital as non-financial assets — education, taste, cultural knowledge — that confer social status and advantage, often reproducing class inequality.','hard'),
('cb161616-0000-0000-0000-000000000007','culture','What does "ethnocentrism" mean?','["Pride in one''s ethnic heritage","Evaluating other cultures through the lens of one''s own culture, often considering it superior","The study of ethnic minorities","Equal appreciation of all cultures"]',1,'Ethnocentrism is the tendency to view the world primarily from the perspective of one''s own culture, often with the implicit assumption that it is superior.','easy'),
('cb161616-0000-0000-0000-000000000008','culture','Carnival celebrations in Brazil most directly derive from which cultural traditions?','["Indigenous Amazonian traditions alone","A blend of African, Indigenous, and European (especially Portuguese) traditions","Spanish colonial traditions","French Catholic traditions"]',1,'Brazilian Carnival fuses African music, dance, and spiritual traditions brought by enslaved people with European (Portuguese Catholic) pre-Lent celebrations and Indigenous elements.','medium'),
('cb161616-0000-0000-0000-000000000009','culture','What is "meme theory" in cultural studies?','["The study of internet jokes","The idea that cultural ideas spread and evolve like genetic traits, proposed by Richard Dawkins","The theory that culture is determined by economics","The study of how myths are created"]',1,'Richard Dawkins coined "meme" in "The Selfish Gene" (1976) to describe units of cultural transmission that replicate, mutate, and are selected analogously to genes.','hard'),
('cb161616-0000-0000-0000-000000000010','culture','The French Revolutionary calendar attempted to replace the 7-day week with a 10-day week. How long did it last?','["2 years","6 years","12 years","25 years"]',2,'The French Republican Calendar was introduced in 1793 and abolished by Napoleon in 1806 — lasting about 12 years before workers'' resistance and practicality led to its end.','hard'),
('cb161616-0000-0000-0000-000000000011','culture','What is the "Sapir-Whorf hypothesis" often called in cultural studies?','["Cultural determinism","Linguistic relativity","Symbolic interactionism","Social constructivism"]',1,'In cultural and linguistic studies, the Sapir-Whorf hypothesis is commonly called linguistic relativity — the idea that the language one speaks shapes how one perceives and thinks about the world.','medium'),
('cb161616-0000-0000-0000-000000000012','culture','What does "globalisation" primarily describe?','["The spread of Western culture only","The increasing interconnection of economies, cultures, and societies worldwide","The homogenisation of all world cultures","The economic dominance of multinational corporations"]',1,'Globalisation describes the growing interconnection of economies, cultures, and societies through trade, technology, and migration — a complex process with both homogenising and diversifying effects.','easy'),
('cb161616-0000-0000-0000-000000000013','culture','The Confucian concept of "face" (mianzi) in East Asian cultures relates to what?','["Physical appearance","Social reputation, dignity, and prestige in the eyes of others","Family loyalty","Academic achievement"]',1,'Mianzi (face) refers to social reputation and dignity in Chinese and broader East Asian cultures — losing face publicly can be deeply damaging, and maintaining face governs many social interactions.','medium'),
('cb161616-0000-0000-0000-000000000014','culture','What is the name of the UNESCO list that protects cultural traditions and practices?','["World Heritage Sites","Intangible Cultural Heritage list","Cultural Diversity Index","Global Arts Registry"]',1,'UNESCO''s Intangible Cultural Heritage list (established 2003) protects living cultural practices — oral traditions, performing arts, rituals, and traditional crafts.','medium'),
('cb161616-0000-0000-0000-000000000015','culture','Which anthropologist wrote "Coming of Age in Samoa" (1928), arguing that culture shapes adolescent experience more than biology?','["Claude Lévi-Strauss","Ruth Benedict","Bronisław Malinowski","Margaret Mead"]',3,'Margaret Mead''s controversial "Coming of Age in Samoa" argued that the stress of Western adolescence is cultural, not biological — a landmark in the nature vs. nurture debate.','medium')
ON CONFLICT (id) DO NOTHING;

-- ---- GEOGRAPHY (be171717) ----
INSERT INTO trivia_questions (id, category_id, question, choices, correct_index, explanation, difficulty) VALUES
('be171717-0000-0000-0000-000000000001','geography','The Mercator projection distorts which property of geographic features?','["Direction","Shape","Area","Distance along meridians"]',2,'The Mercator projection preserves angles (conformal) but drastically distorts area — making Greenland appear similar in size to Africa, though Africa is 14 times larger.','medium'),
('be171717-0000-0000-0000-000000000002','geography','What is a "rain shadow"?','["The area of heaviest rainfall on a mountain","The dry area on the leeward side of a mountain where air descends dry after losing moisture climbing the windward side","A region of perpetual cloud cover","The shadow cast by storm clouds"]',1,'A rain shadow forms on the leeward side of a mountain range: moist air rises, cools, and drops rain on the windward side, then descends dry on the other side.','medium'),
('be171717-0000-0000-0000-000000000003','geography','The 1884–85 Berlin Conference divided Africa among European powers without the presence of which group?','["Arab traders","African representatives","Church officials","Asian diplomats"]',1,'The Berlin Conference was attended only by European powers and the United States — not a single African was present when the continent was carved up.','medium'),
('be171717-0000-0000-0000-000000000004','geography','Which country is the largest by land area in the world?','["Canada","China","United States","Russia"]',3,'Russia is the largest country in the world by land area, covering approximately 17.1 million km² — nearly twice the size of the second-largest, Canada.','easy'),
('be171717-0000-0000-0000-000000000005','geography','The Atacama Desert is one of Earth''s driest places. What causes its extreme aridity?','["Its tropical location","A rain shadow created by the Andes mountains","Distance from the ocean","Lack of vegetation"]',1,'The Atacama lies in the rain shadow of the Andes; moisture from the Atlantic is blocked by the mountains, and cold Pacific currents suppress rainfall on the western side.','medium'),
('be171717-0000-0000-0000-000000000006','geography','What mathematical impossibility applies to all flat map projections?','["No flat map can show true direction","No flat map can show both accurate area and accurate shape simultaneously","No flat map can show longitude accurately","No flat map can represent polar regions"]',1,'Gauss proved that you cannot create a flat map that is both conformal (shape-preserving) and equal-area — every projection sacrifices one for the other.','hard'),
('be171717-0000-0000-0000-000000000007','geography','The Nile is the longest river in the world. Which two countries share most of its length?','["Egypt and Sudan","Ethiopia and Kenya","Uganda and Tanzania","Libya and Chad"]',0,'The Nile flows primarily through Sudan and Egypt before emptying into the Mediterranean — though its headwaters originate in Ethiopia and Uganda.','easy'),
('be171717-0000-0000-0000-000000000008','geography','What is "plate tectonics"?','["The study of geological time periods","The theory that Earth''s lithosphere is divided into moving plates whose interactions cause earthquakes, volcanism, and mountain building","The measurement of soil composition","The study of ocean floor sediment"]',1,'Plate tectonics describes how Earth''s lithosphere is divided into rigid plates that move on the underlying mantle, driving earthquakes, volcanism, and the formation of mountains and ocean basins.','easy'),
('be171717-0000-0000-0000-000000000009','geography','What is the approximate population of Africa as of the 2020s?','["800 million","1.2 billion","1.4 billion","2 billion"]',2,'Africa''s population was approximately 1.4 billion in the early 2020s, making it home to about 18% of the world''s population — the second-most populous continent.','medium'),
('be171717-0000-0000-0000-000000000010','geography','The Mariana Trench, the deepest point on Earth, is located in which ocean?','["Atlantic Ocean","Indian Ocean","Arctic Ocean","Pacific Ocean"]',3,'The Mariana Trench, with the Challenger Deep at approximately 11 km below sea level, is located in the western Pacific Ocean east of the Mariana Islands.','easy'),
('be171717-0000-0000-0000-000000000011','geography','What is the term for a long, narrow inlet of the sea between cliffs, typically formed by glacial erosion?','["Estuary","Delta","Fjord","Canyon"]',2,'A fjord is a long, narrow inlet with steep sides, carved by glacial erosion and later flooded by the sea — classic examples are found in Norway, New Zealand, and Chile.','easy'),
('be171717-0000-0000-0000-000000000012','geography','Which geographic term describes the imaginary line at 0 degrees longitude?','["Equator","International Date Line","Prime Meridian","Tropic of Cancer"]',2,'The Prime Meridian (0° longitude) passes through Greenwich, England, and serves as the reference line from which longitudes east and west are measured.','easy'),
('be171717-0000-0000-0000-000000000013','geography','What is the "demographic transition model"?','["A theory of immigration patterns","A model describing how countries progress from high birth and death rates to low birth and death rates as they develop","A tool for predicting war between nations","A description of urban-rural migration"]',1,'The demographic transition model describes the historical shift from high birth and death rates (pre-industrial) through falling death rates, then falling birth rates, to low rates of both (post-industrial).','hard'),
('be171717-0000-0000-0000-000000000014','geography','Which is the only country to share a land border with both the US and Canada?','["No country borders both","Mexico","Cuba","Haiti"]',0,'No country borders both the US and Canada — Mexico borders only the US (to the south), while Canada borders only the US (to the south) among contiguous territories.','hard'),
('be171717-0000-0000-0000-000000000015','geography','The "Fertile Crescent," considered the cradle of agriculture, spans which modern countries?','["Egypt and Libya","Iraq, Syria, Lebanon, Israel, Jordan, and parts of Turkey and Iran","Pakistan and Afghanistan","India and Bangladesh"]',1,'The Fertile Crescent spans the river valleys of the Tigris and Euphrates (Iraq), the Levant (Syria, Lebanon, Israel, Jordan), and extends into southern Turkey and western Iran.','medium')
ON CONFLICT (id) DO NOTHING;
